import { apiUrl } from "./api";
async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(apiUrl(path),{credentials:"include",cache:"no-store",...init});if(!response.ok){const body=await response.json().catch(()=>({})) as {detail?:string};throw new Error(body.detail??`Case request failed (${response.status})`)}return response.json() as Promise<T>}
export type CaseAlternative={id:string;strategy_type:string;parameters:Record<string,unknown>;expected_impact:Record<string,unknown>;cost:number|null;time_to_effect_hours:number|null;success_probability:number|null;side_effects:Array<Record<string,unknown>>;score:number;score_dimensions:Record<string,number>;ranking:number;evidence:Array<Record<string,unknown>>;feasibility:string};
export type OperationalCase={id:string;case_type:string;title:string;summary?:string|null;severity:string;status:string;priority_score:number;confidence:number;decision_deadline?:string|null;expected_impact_at?:string|null;recovery_state:string;responsible_team?:string|null;entities:Array<{type:string;id:string;label:string;relationship:string;importance:number}>;causes?:Array<{type:string;description:string;confidence:number}>;exposures?:Array<{metric:string;baseline:number|null;projected:number|null;delta:number|null;unit:string;methodology:string;confidence:number}>;decision?:{id:string;status:string;recommended_alternative_id?:string|null;selected_alternative_id?:string|null;alternatives:CaseAlternative[]}|null;action_plan?:{id:string;status:string;strategy_type:string;objective:string;steps:Array<{id:string;sequence:number;title:string;owner_team:string;status:string;action_intent_id?:string|null}>}|null};
export const listCases=()=>request<OperationalCase[]>("/api/v1/cases");
export type DecisionInboxItem={id:string;source_type:string;source_id:string;title:string;status:string;href:string;deadline:string|null;priority:number;owner:string|null;case_id:string|null;alternative_count:number|null};
export const getDecisionInbox=()=>request<DecisionInboxItem[]>("/api/v1/decision-inbox");
export const getCase=(id:string)=>request<OperationalCase>(`/api/v1/cases/${id}`);
export const getCaseTimeline=(id:string)=>request<Array<{type:string;at:string;title:string;source_event_id?:string}>>(`/api/v1/cases/${id}/timeline`);
export const getRecovery=(id:string)=>request<{case_id:string;status:string;verification?:{evidence_completeness:number;confidence:number;failure_reason?:string|null;stability_window_start?:string|null;stability_window_end?:string|null}|null;targets:Array<{id:string;metric:string;operator:string;threshold:number;required_observation_count:number;required_duration_seconds:number;observations:Array<{id:string;value:number;observed_at:string;freshness:string;satisfied:boolean;source:Record<string,unknown>;evidence:Record<string,unknown>}>}>}>(`/api/v1/recoveries/${id}`);
export async function selectCaseDecision(caseId:string,alternativeId:string,reason:string,overrideReason?:string){return request<{decision_id:string;status:string}>(`/api/v1/cases/${caseId}/decisions`,{method:"POST",headers:{"Content-Type":"application/json","X-CSRF-Token":localStorage.getItem("gg_csrf")??""},body:JSON.stringify({alternative_id:alternativeId,reason,override_reason:overrideReason})})}
