"use client";

import Link from "next/link";
import { AlertTriangle, ArrowRight, Bot, CheckCircle2, Clock3, DatabaseZap, GitPullRequestArrow, Sparkles } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { getV2CommandCenter, getV2Context, getV2KPIs } from "@/lib/api";
import { OperatingPulse } from "./OperatingPulse";
import { V2AppShell } from "./V2AppShell";
import { OperationalKPIStrip } from "./OperationalKPIStrip";
import { PlantActivationState } from "./OperationalPrimitives";

export function CommandCenter() {
  const [lossMeasure,setLossMeasure]=useState<"units"|"time"|"value">("units");
  const contextQuery = useQuery({ queryKey: ["v2-context"], queryFn: getV2Context });
  const shift = contextQuery.data?.shifts.find((item) => item.status === "active") ?? contextQuery.data?.shifts[0];
  const commandQuery = useQuery({
    queryKey: ["command-center", contextQuery.data?.plant?.id, shift?.id],
    queryFn: () => getV2CommandCenter(contextQuery.data!.plant!.id, shift?.id),
    enabled: Boolean(contextQuery.data?.plant?.id), refetchInterval: 60_000,
  });
  const kpiQuery=useQuery({queryKey:["v2-kpis",contextQuery.data?.plant?.id,shift?.id],queryFn:()=>getV2KPIs(contextQuery.data!.plant!.id,shift?.id),enabled:Boolean(contextQuery.data?.plant?.id),refetchInterval:60_000});
  if (contextQuery.isLoading) return <div className="v2-loading">Loading plant context…</div>;
  if (contextQuery.error || !contextQuery.data?.plant) return <div className="v2-error"><AlertTriangle/><h1>Plant context is unavailable</h1><p>{contextQuery.error instanceof Error ? contextQuery.error.message : "Sign in or check the API connection."}</p><Link href="/login">Return to sign in</Link></div>;
  const {locale,timezone,currency}=contextQuery.data.plant;
  const number=(value:number)=>new Intl.NumberFormat(locale).format(value);
  const money=(value:number,code=currency)=>new Intl.NumberFormat(locale,{style:"currency",currency:code,maximumFractionDigits:0}).format(value);
  const time=(value:number)=>new Intl.DateTimeFormat(locale,{timeZone:timezone,hour:"2-digit",minute:"2-digit"}).format(new Date(value));
  const lossValue=(item:NonNullable<typeof commandQuery.data>["loss_breakdown"][number])=>lossMeasure==="time"?item.time_impact_minutes:lossMeasure==="value"?(item.financial_impact??0):item.lost_units;
  const lossTotal=commandQuery.data?.loss_breakdown.reduce((sum,item)=>sum+lossValue(item),0)??0;
  const lossLabel=(item:NonNullable<typeof commandQuery.data>["loss_breakdown"][number])=>lossMeasure==="time"?`${number(item.time_impact_minutes)} min`:lossMeasure==="value"?item.financial_impact==null?"Restricted":money(item.financial_impact,item.currency):`${number(item.lost_units)} units`;
  const awaitingActivation = Boolean(commandQuery.data && !shift && commandQuery.data.pulse.target === 0 && commandQuery.data.top_deviations.length === 0);
  return <V2AppShell context={contextQuery.data}>
    <div className="v2-page-heading"><div><h1>Plant Command Center</h1><span>{contextQuery.data.plant.name} <b>·</b> {shift?.name ?? "Current shift"}</span></div><div className="v2-last-update"><DatabaseZap/> Updated {commandQuery.dataUpdatedAt ? time(commandQuery.dataUpdatedAt) : "—"}</div></div>
    {awaitingActivation ? <PlantActivationState/> : <>{commandQuery.data?.role_focus&&<section className="v2-role-focus"><div><span>Your operating focus · {commandQuery.data.role_focus.role.replaceAll("_"," ")}</span><strong>{commandQuery.data.role_focus.question}</strong></div><p><b>{commandQuery.data.role_focus.attention_count}</b> relevant active deviations</p></section>}
    {kpiQuery.data&&<OperationalKPIStrip board={kpiQuery.data}/>} 
    {commandQuery.data&&<><section className="v2-recovery-value-strip"><div><span>Operational value at risk</span><strong>{commandQuery.data.recovery_summary.value_at_risk==null?"Restricted":money(commandQuery.data.recovery_summary.value_at_risk)}</strong></div><div><span>Recovery in progress</span><strong>{commandQuery.data.recovery_summary.value_addressed==null?"Restricted":money(commandQuery.data.recovery_summary.value_addressed)}</strong></div><div><span>Verified recovered today</span><strong>{commandQuery.data.recovery_summary.verified_recovered_value_today==null?"Restricted":money(commandQuery.data.recovery_summary.verified_recovered_value_today)}</strong></div></section>
    <section className="v2-panel v2-recovery-opportunities"><div className="v2-panel-heading"><div><p>Recovery opportunities</p><h2>Value that can still be protected</h2></div><span>{commandQuery.data.recovery_opportunities.length}</span></div><div className="v2-recovery-opportunity-grid">{commandQuery.data.recovery_opportunities.slice(0,4).map(row=><Link href={`/v2/deviations/${row.deviation_id}`} key={row.id}><header><span className={`v2-state ${row.severity}`}>{row.status.replaceAll("_"," ")}</span><strong>{row.business_exposure_amount==null?"Restricted":money(row.business_exposure_amount,row.currency??currency)} at risk</strong></header><h3>{row.title}</h3><p>{row.strategy?.title??"Recovery options are being assessed"}</p><small>{row.strategy?`Expected recovery ${number(row.strategy.expected_recovered_units??0)} units · ${Math.round((row.strategy.estimated_success_probability??0)*100)}% estimated success`:"Waiting for current operational context"}</small><footer>{row.decision_required?"Decision needed":"Recovery coordinated"}<ArrowRight/></footer></Link>)}</div></section></>}
    {commandQuery.isLoading ? <div className="v2-skeleton-grid"><i/><i/><i/></div> : commandQuery.error || !commandQuery.data ? <div className="v2-degraded"><AlertTriangle/><div><strong>Operational data could not be loaded.</strong><p>Forecasts and deviations may be unavailable. {commandQuery.error instanceof Error ? commandQuery.error.message : ""}</p></div><button onClick={() => commandQuery.refetch()}>Retry</button></div> : <div className="v2-command-grid">
      <OperatingPulse pulse={commandQuery.data.pulse}/>
      <section className="v2-panel v2-decisions"><div className="v2-panel-heading"><div><p>Decisions required</p><h2>Leadership attention</h2></div><span>{commandQuery.data.decisions_required.length}</span></div>{commandQuery.data.decisions_required.length ? <div className="v2-decision-stack">{commandQuery.data.decisions_required.map(item=><Link href={`/v2/deviations/${item.deviation_id}`} key={item.id}><GitPullRequestArrow/><div><strong>{item.decision}</strong><span>{item.affected_object}</span><small>{item.need_by?`Need by ${time(new Date(item.need_by).getTime())}`:"Action required"}</small></div><ArrowRight/></Link>)}</div> : <div className="v2-empty-compact"><CheckCircle2/><strong>No decisions are waiting</strong><p>Recovery work is moving without a leadership block.</p></div>}</section>
      <section className="v2-panel v2-loss"><div className="v2-panel-heading"><div><p>Why output is at risk</p><h2>Loss breakdown</h2></div><div className="v2-measure" aria-label="Loss measure">{[["units","Units"],["time","Time"],...(commandQuery.data.role_focus.show_financial_value?[["value",currency]]:[])].map(([value,label])=><button key={value} className={lossMeasure===value?"active":""} aria-pressed={lossMeasure===value} onClick={()=>setLossMeasure(value as typeof lossMeasure)}>{label}</button>)}</div></div>{commandQuery.data.loss_breakdown.length?<><div className="v2-loss-bars">{commandQuery.data.loss_breakdown.map((item,index)=><Link href={`/v2/operations?loss=${encodeURIComponent(item.category)}`} key={item.category}><div><span>{item.category.replaceAll("_"," ")}</span><strong>{lossLabel(item)}</strong></div><i style={{width:`${Math.max(lossValue(item)/Math.max(lossTotal,1)*100,4)}%`}} data-rank={index}/></Link>)}</div><p className="v2-provisional">{lossMeasure==="value"?money(lossTotal):`${number(lossTotal)} ${lossMeasure==="time"?"minutes":"units"}`} attributed across active operational deviations.</p></>:<div className="v2-empty-compact"><CheckCircle2/><strong>No attributable loss</strong><p>Active events are not currently reducing the production forecast.</p></div>}</section>
      <section className="v2-panel v2-deviations"><div className="v2-panel-heading"><div><p>Active deviations</p><h2>Highest operational impact</h2></div><span>{commandQuery.data.top_deviations.length}</span></div><div className="v2-deviation-list">{commandQuery.data.top_deviations.map((item) => <Link className={commandQuery.data.role_focus.relevant_deviation_ids.includes(item.id)?"role-relevant":""} key={item.id} href={`/v2/deviations/${item.id}`}><div><span className={`v2-state ${item.severity}`}>{item.severity}</span>{commandQuery.data.role_focus.relevant_deviation_ids.includes(item.id)&&<small>Relevant to your role</small>}<h3>{item.title}</h3><p>{number(item.lost_units)} units · {item.financial_impact==null?"financial value restricted":money(item.financial_impact,item.currency)}</p></div><ArrowRight/></Link>)}</div></section>
      <section className="v2-panel v2-gigi-activity"><div className="v2-panel-heading"><div><p>Gigi activity</p><h2>What GenuineGigs is handling</h2></div><Bot/></div><div className="v2-activity-stream">{commandQuery.data.automation_activity.length?commandQuery.data.automation_activity.map(item=><div key={item.id}><Sparkles/><div><strong>{item.summary}</strong><p>{item.type.replaceAll("."," ")} · {time(new Date(item.at).getTime())}</p></div></div>):<div className="v2-activity-item"><Clock3/><div><strong>Production recovery is being monitored</strong><p>No new governed activity has been recorded in this shift.</p></div></div>}</div></section>
      <section className="v2-panel v2-data-health"><div className="v2-panel-heading"><div><p>Data health</p><h2>Operational sources</h2></div><span>{commandQuery.data.data_health.length}</span></div>{commandQuery.data.data_health.length ? commandQuery.data.data_health.map((source, index) => <div className="v2-health-row" key={String(source.connection_id ?? index)}><span><i className={String(source.state)}/>{String(source.source)}</span><strong>{String(source.state)}</strong></div>) : <p>No operational source is configured. Forecasts use the API-backed demonstration dataset.</p>}</section>
    </div>}</>}
  </V2AppShell>;
}
