"use client";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Check, Cpu, Database, Factory, Plus, RadioTower, Save } from "lucide-react";
import { getV2Edge, getV2Setup, saveV2SetupArea, saveV2SetupLine, updateV2Setup } from "@/lib/api";
import { V2QueryFrame } from "./V2QueryFrame";
import { DetectorRules } from "./DetectorRules";

function Content() {
  const client=useQueryClient();
  const setup=useQuery({queryKey:["v2-setup"],queryFn:getV2Setup});
  const edge=useQuery({queryKey:["v2-edge"],queryFn:getV2Edge});
  const [area,setArea]=useState({id:"",name:"",code:""});
  const [line,setLine]=useState({id:"",area_id:"",name:"",code:"",rate:"",contribution:""});
  const [useCase,setUseCase]=useState("production_loss");
  const [domains,setDomains]=useState("production, machines, quality, maintenance");
  const [rejectionTarget,setRejectionTarget]=useState("0.04");
  const [downtimeTarget,setDowntimeTarget]=useState("15");
  useEffect(()=>{if(!setup.data)return;setUseCase(setup.data.primary_use_case??"production_loss");setDomains(setup.data.enabled_data_domains.join(", "));setRejectionTarget(String(setup.data.configuration.kpi_targets?.rejection_rate??.04));setDowntimeTarget(String(setup.data.configuration.kpi_targets?.downtime_minutes??15))},[setup.data]);
  const refresh=()=>client.invalidateQueries({queryKey:["v2-setup"]});
  const areaMutation=useMutation({mutationFn:()=>saveV2SetupArea({name:area.name,code:area.code},area.id||undefined),onSuccess:()=>{setArea({id:"",name:"",code:""});refresh()}});
  const lineMutation=useMutation({mutationFn:()=>saveV2SetupLine({area_id:line.area_id,name:line.name,code:line.code,standard_good_rate_per_minute:Number(line.rate),contribution_per_good_unit:Number(line.contribution)},line.id||undefined),onSuccess:()=>{setLine({id:"",area_id:"",name:"",code:"",rate:"",contribution:""});refresh()}});
  const profileMutation=useMutation({mutationFn:()=>updateV2Setup({activation_stage:"use_case",primary_use_case:useCase,enabled_data_domains:domains.split(",").map(value=>value.trim()).filter(Boolean),production_calendar:setup.data?.configuration.production_calendar??{},kpi_targets:{...(setup.data?.configuration.kpi_targets??{}),rejection_rate:Number(rejectionTarget),downtime_minutes:Number(downtimeTarget)},loss_categories:setup.data?.configuration.loss_categories??[],escalation_rules:setup.data?.configuration.escalation_rules??[],value_formulas:setup.data?.configuration.value_formulas??[],action_policies:setup.data?.configuration.action_policies??[],completed_stages:["plant","data","use_case"]}),onSuccess:refresh});
  const error=(areaMutation.error||lineMutation.error||profileMutation.error) as Error|null;
  const heading=<div className="v2-page-heading"><div><p>Operational setup</p><h1>Activate one plant, one data path, one use case.</h1><span>Guided configuration for operating context—not a giant technical wizard.</span></div></div>;
  if(setup.isLoading)return <>{heading}<div className="v2-loading-region">Loading the governed plant configuration…</div></>;
  if(setup.error)return <>{heading}<div className="v2-degraded"><AlertTriangle/><div><strong>Operational setup could not be loaded.</strong><p>No configuration changes are available until the authoritative setup profile is restored.</p></div><button onClick={()=>setup.refetch()}>Retry</button></div></>;
  return <>{heading}<div className="v2-activation-flow">{[["Plant",Factory],["Data",Database],["Use case",Check]].map(([label,Icon],index)=><div className={setup.data?.completed_stages.length&&index<setup.data.completed_stages.length?"done":""} key={String(label)}><i><Icon/></i><strong>{String(label)}</strong><span>{index===0?`${setup.data?.hierarchy.areas??0} areas · ${setup.data?.hierarchy.lines??0} lines`:index===1?`${setup.data?.enabled_data_domains.length??0} domains`:setup.data?.primary_use_case?.replaceAll("_"," ")}</span></div>)}</div>
  <div className="v2-setup-edit-grid"><section className="v2-panel"><div className="v2-panel-heading"><div><p>Plant hierarchy</p><h2>Areas and lines</h2></div><Factory/></div><div className="v2-setup-records"><h3>Areas</h3>{setup.data?.hierarchy.area_records.map(row=><button key={row.id} onClick={()=>setArea(row)}><strong>{row.name}</strong><span>{row.code}</span></button>)}<form onSubmit={event=>{event.preventDefault();areaMutation.mutate()}}><input aria-label="Area name" placeholder="Area name" value={area.name} onChange={event=>setArea({...area,name:event.target.value})}/><input aria-label="Area code" placeholder="Code" value={area.code} onChange={event=>setArea({...area,code:event.target.value})}/><button disabled={!area.name||!area.code}><Plus/>{area.id?"Update area":"Add area"}</button></form><h3>Lines</h3>{setup.data?.hierarchy.line_records.map(row=><button key={row.id} onClick={()=>setLine({id:row.id,area_id:row.area_id,name:row.name,code:row.code,rate:String(row.standard_good_rate_per_minute),contribution:String(row.contribution_per_good_unit)})}><strong>{row.name}</strong><span>{row.code}</span></button>)}<form className="line" onSubmit={event=>{event.preventDefault();lineMutation.mutate()}}><select aria-label="Line area" value={line.area_id} onChange={event=>setLine({...line,area_id:event.target.value})}><option value="">Select area</option>{setup.data?.hierarchy.area_records.map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select><input aria-label="Line name" placeholder="Line name" value={line.name} onChange={event=>setLine({...line,name:event.target.value})}/><input aria-label="Line code" placeholder="Code" value={line.code} onChange={event=>setLine({...line,code:event.target.value})}/><input aria-label="Standard units per minute" type="number" step="0.01" placeholder="Units/min" value={line.rate} onChange={event=>setLine({...line,rate:event.target.value})}/><input aria-label="Contribution per unit" type="number" step="0.01" placeholder="Contribution/unit" value={line.contribution} onChange={event=>setLine({...line,contribution:event.target.value})}/><button disabled={!line.area_id||!line.name||!line.code||!line.rate}><Plus/>{line.id?"Update line":"Add line"}</button></form></div></section>
  <section className="v2-panel"><div className="v2-panel-heading"><div><p>Operating contract</p><h2>Use case and rules</h2></div><Save/></div><form className="v2-setup-rules" onSubmit={event=>{event.preventDefault();profileMutation.mutate()}}><label>Primary use case<select value={useCase} onChange={event=>setUseCase(event.target.value)}><option value="production_loss">Production loss recovery</option><option value="material_readiness">Material readiness</option><option value="quality_recovery">Quality recovery</option><option value="maintenance_reliability">Maintenance reliability</option></select></label><label>Enabled data domains<input value={domains} onChange={event=>setDomains(event.target.value)}/><small>Comma-separated canonical domains</small></label><label>Rejection target<input type="number" min="0" max="1" step="0.001" value={rejectionTarget} onChange={event=>setRejectionTarget(event.target.value)}/></label><label>Downtime threshold (minutes)<input type="number" min="1" value={downtimeTarget} onChange={event=>setDowntimeTarget(event.target.value)}/></label><button><Save/> Save operating rules</button></form>{error&&<p className="v2-form-error" role="alert">{error.message}</p>}</section></div>
  {setup.data&&<DetectorRules rules={setup.data.detectors}/>}<section className="v2-panel" id="edge"><div className="v2-panel-heading"><div><p>OT boundary</p><h2>Plant edge health</h2></div><RadioTower/></div>{edge.isLoading?<div className="v2-loading-region">Reading edge gateway health…</div>:edge.error?<div className="v2-degraded"><AlertTriangle/><div><strong>Edge health is unavailable.</strong><p>Machine context must be treated as stale until gateway health returns.</p></div><button onClick={()=>edge.refetch()}>Retry</button></div>:edge.data?.gateways.length?edge.data.gateways.map(gateway=><article className="v2-edge-card" key={gateway.id}><header><Cpu/><div><strong>{gateway.name}</strong><span>Runtime {gateway.runtime_version} · config v{gateway.config_version}</span></div><span className={`v2-state ${gateway.status}`}>{gateway.status}</span></header><dl><div><dt>Transport</dt><dd>{gateway.transport}</dd></div><div><dt>Boundary</dt><dd>{gateway.outbound_only?"Outbound only":"Review required"}</dd></div><div><dt>Buffer</dt><dd>{gateway.buffer_depth} pending</dd></div></dl>{gateway.mappings.map(row=><div className="v2-edge-map" key={row.id}><span>{row.protocol}</span><code>{row.source_address}</code><b>→</b><strong>{row.canonical_signal}</strong></div>)}</article>):<div className="v2-empty-compact"><RadioTower/><strong>No edge gateway registered</strong><p>Register a signed outbound-only gateway before enabling machine context.</p></div>}</section></>;
}
export function OperationalSetup(){return <V2QueryFrame>{()=> <Content/>}</V2QueryFrame>}
