"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowRight, BellRing, CheckCheck, FilePenLine, Search, Send, Sparkles } from "lucide-react";
import { generateV2Handover, getV2Notifications, getV2PredictiveRisks, getV2ShiftBriefing, publishV2Handover, searchV2, updateV2Handover, verifyV2Handover, type V2Context, type V2ShiftBriefing } from "@/lib/api";
import { V2QueryFrame } from "./V2QueryFrame";
import { useV2Formatting } from "./V2Formatting";
import { DegradedDataBanner, EmptyOperationalState, SeverityBadge } from "./OperationalPrimitives";

function Content({ context }: { context: V2Context }) {
  const format=useV2Formatting();
  const shift = context.shifts.find(row => row.status === "active") ?? context.shifts[0];
  const risks = useQuery({ queryKey: ["predictive-risks"], queryFn: getV2PredictiveRisks });
  const notifications = useQuery({ queryKey: ["v2-notifications"], queryFn: getV2Notifications });
  const [view, setView] = useState<"start"|"handover">("start");
  const briefing = useQuery({ queryKey: ["shift-briefing", shift?.id, view], queryFn: () => getV2ShiftBriefing(shift.id, view), enabled: Boolean(shift), retry:false });
  const [term, setTerm] = useState("");
  const search = useQuery({ queryKey: ["v2-search", term], queryFn: () => searchV2(term), enabled: term.trim().length > 1 });
  return <><div className="v2-page-heading"><div><p>Operating briefing</p><h1>What changed, what is likely, and what needs action.</h1><span>Grounded in the active shift—not a generic AI summary.</span></div></div><div className="v2-filter-row"><button className={view==="start"?"active":""} onClick={()=>setView("start")}>Shift start</button><button className={view==="handover"?"active":""} onClick={()=>setView("handover")}>End-of-shift handover</button></div>
    <div className="v2-command-search"><Search/><input aria-label="Search plant operations" placeholder="Search WO-482, CNC-04, RM-218, Fault 701…" value={term} onChange={event => setTerm(event.target.value)}/></div>
    {search.isFetching&&<div className="v2-loading-region">Searching connected plant records…</div>}{search.error&&<DegradedDataBanner title="Operational search is unavailable." detail="No result is shown because connected-record retrieval failed." onRetry={()=>search.refetch()}/>} {search.data?.groups.length ? <section className="v2-search-results">{search.data.groups.map(group => <div key={group.entity}><h2>{group.entity}</h2>{group.results.map(row => <Link href={row.href} key={row.id}><strong>{row.label}</strong><span>{row.context}</span><ArrowRight/></Link>)}</div>)}</section> : term.trim().length>1&&!search.isFetching&&!search.error?<EmptyOperationalState title="No connected record found" detail="Try a line, asset, work order, material or fault code."/>:null}
    <div className="v2-briefing-grid">{view === "handover" ? briefing.isLoading?<div className="v2-loading-region">Loading shift handover…</div>:<HandoverPanel shiftId={shift?.id} handover={briefing.data} missing={briefing.isError}/> : briefing.isLoading?<div className="v2-loading-region">Loading the verified shift briefing…</div>:briefing.error?<DegradedDataBanner title="Shift briefing is unavailable." detail="Priorities are not shown because the grounded briefing could not be retrieved." onRetry={()=>briefing.refetch()}/>:<section className="v2-panel v2-shift-brief"><div className="v2-panel-heading"><div><p>{shift?.name ?? "Shift"}</p><h2>{briefing.data?.title ?? "No published briefing"}</h2></div><Sparkles/></div><p>{briefing.data?.summary}</p><ol>{briefing.data?.priorities.map(row => <li key={row.title}><strong>{row.title}</strong></li>)}</ol>{briefing.data?.verified_by_user_id && <footer>Supervisor verified · Published {format.time(briefing.data.published_at ?? briefing.data.generated_at)}</footer>}</section>}
      <section className="v2-panel"><div className="v2-panel-heading"><div><p>Forward look</p><h2>Predictive risks</h2></div><AlertTriangle/></div>{risks.isLoading?<div className="v2-loading-region">Evaluating current risk evidence…</div>:risks.error?<DegradedDataBanner title="Predictive risks are unavailable." detail="No prediction is presented without its current evidence." onRetry={()=>risks.refetch()}/>:risks.data?.length?<div className="v2-risk-list">{risks.data.map(row => <article key={row.key}><SeverityBadge severity={row.severity}/><strong>{row.title}</strong><p>{Math.round(row.probability * 100)}% probability · {row.predicted_impact} {row.unit}</p><small>{row.recommended_action}</small><em>{row.confidence} confidence · {row.evidence.length} evidence</em></article>)}</div>:<EmptyOperationalState title="No predictive risk exceeds its threshold" detail="The forward look will surface a risk when evidence supports action."/>}</section>
      <section className="v2-panel v2-briefing-wide"><div className="v2-panel-heading"><div><p>Grouped attention</p><h2>Operational notifications</h2></div><BellRing/></div>{notifications.isLoading?<div className="v2-loading-region">Loading grouped operational attention…</div>:notifications.error?<DegradedDataBanner title="Notifications are unavailable." detail="Do not infer that no escalation or action is waiting." onRetry={()=>notifications.refetch()}/>:notifications.data?.length?<div className="v2-notification-list">{notifications.data.map(row => row.href ? <Link href={row.href} key={row.id}><SeverityBadge severity={row.severity}/><div><strong>{row.title}</strong><p>{row.summary}</p></div><ArrowRight/></Link> : null)}</div>:<EmptyOperationalState title="No grouped attention is waiting" detail="New actions and escalations will be grouped here by operational consequence."/>}</section></div>
  </>;
}

function HandoverPanel({shiftId,handover,missing}:{shiftId?:string;handover?:V2ShiftBriefing;missing:boolean}){const format=useV2Formatting();const client=useQueryClient();const [summary,setSummary]=useState("");useEffect(()=>setSummary(handover?.summary??""),[handover?.summary]);const refresh=()=>client.invalidateQueries({queryKey:["shift-briefing",shiftId,"handover"]});const generate=useMutation({mutationFn:()=>generateV2Handover(shiftId!),onSuccess:refresh});const save=useMutation({mutationFn:()=>updateV2Handover(shiftId!,{summary,priorities:handover?.priorities??[],losses:handover?.losses??[],carry_over:handover?.carry_over??[]}),onSuccess:refresh});const verify=useMutation({mutationFn:()=>verifyV2Handover(shiftId!),onSuccess:refresh});const publish=useMutation({mutationFn:()=>publishV2Handover(shiftId!),onSuccess:refresh});if(missing)return <section className="v2-panel v2-shift-brief v2-handover-empty"><FilePenLine/><h2>Generate the shift handover</h2><p>Gigi will draft plan, actual, main losses and carry-over. A supervisor must review it before publication.</p><button onClick={()=>generate.mutate()} disabled={!shiftId||generate.isPending}>{generate.isPending?"Generating…":"Generate draft"}</button></section>;return <section className="v2-panel v2-shift-brief"><div className="v2-panel-heading"><div><p>{handover?.status} handover</p><h2>{handover?.title}</h2></div><Sparkles/></div>{handover?.status==="draft"?<textarea aria-label="Handover summary" value={summary} onChange={event=>setSummary(event.target.value)}/>:<p>{handover?.summary}</p>}<div className="v2-handover-metrics"><div><span>Plan</span><strong>{String(handover?.metrics.target??"—")}</strong></div><div><span>Actual</span><strong>{String(handover?.metrics.actual??"—")}</strong></div><div><span>Forecast</span><strong>{String(handover?.metrics.forecast??"—")}</strong></div></div><h3>Carry-over</h3><ol>{handover?.carry_over.map((row,index)=><li key={index}><strong>{String(row.title??"Open issue")}</strong><span>{String(row.owner_role??"Owner pending")}</span></li>)}</ol><div className="v2-handover-actions">{handover?.status==="draft"&&<><button className="secondary" onClick={()=>save.mutate()}><FilePenLine/> Save edits</button><button onClick={()=>verify.mutate()}><CheckCheck/> Verify</button></>}{handover?.status==="verified"&&<button onClick={()=>publish.mutate()}><Send/> Publish handover</button>}</div>{handover?.verified_by_user_id&&<footer>Supervisor verified{handover.published_at?` · Published ${format.time(handover.published_at)}`:" · Awaiting publication"}</footer>}</section>}
export function OperatingBriefing() { return <V2QueryFrame>{context => <Content context={context}/>}</V2QueryFrame>; }
