"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, BookOpenCheck, FileWarning, Search, ShieldCheck } from "lucide-react";
import { getV2Knowledge } from "@/lib/api";
import { V2QueryFrame } from "./V2QueryFrame";

function Content(){const [term,setTerm]=useState("");const query=useQuery({queryKey:["v2-knowledge",term],queryFn:()=>getV2Knowledge(term)});return <><div className="v2-page-heading"><div><p>Plant knowledge</p><h1>Use the approved instruction that applies now.</h1><span>SOPs, manuals and control knowledge with revision, scope, validity and visible citations.</span></div></div><div className="v2-command-search"><Search/><input aria-label="Search approved plant knowledge" placeholder="Search fault 701, BR-28, quality hold…" value={term} onChange={event=>setTerm(event.target.value)}/></div>{query.isLoading?<div className="v2-loading-region">Searching approved active revisions…</div>:query.error?<div className="v2-degraded"><AlertTriangle/><div><strong>Approved plant knowledge is unavailable.</strong><p>Do not rely on an unverified or superseded instruction. Restore the knowledge source, then retry.</p></div><button onClick={()=>query.refetch()}>Retry</button></div>:<><div className="v2-knowledge-policy"><ShieldCheck/><div><strong>Approved active revisions only</strong><p>{query.data?.retrieval_policy}</p></div></div>{!query.data?.results.length?<div className="v2-empty-compact"><BookOpenCheck/><strong>No approved instruction matched</strong><p>Try an asset, fault code, material, process or SOP title. Excluded revisions remain unavailable by design.</p></div>:<div className="v2-knowledge-grid"><section>{query.data.results.map(row=><article className="v2-knowledge-result" key={row.document.id}><header><BookOpenCheck/><div><span>{row.document.document_type.replaceAll("_"," ")} · Revision {row.document.revision}</span><h2>{row.document.title}</h2></div><span className="v2-state available">approved</span></header><blockquote>{row.match.excerpt}</blockquote><footer><div><strong>{row.match.section??"Document section"}</strong><span>{row.match.page??"Page not supplied"} · relevance {Math.round(row.match.score*100)}%</span></div><div>{row.document.asset_ids.map(id=><span key={id}>{id}</span>)}{row.document.process_codes.map(id=><span key={id}>{id}</span>)}</div></footer></article>)}</section><aside className="v2-panel v2-excluded-knowledge"><div className="v2-panel-heading"><div><p>Revision guard</p><h2>Excluded material</h2></div><FileWarning/></div>{query.data.excluded_revisions.map(row=><div key={row.id}><strong>{row.title} · {row.revision}</strong><span>{row.warning}</span></div>)}</aside></div>}</>}</>}
export function PlantKnowledge(){return <V2QueryFrame>{()=> <Content/>}</V2QueryFrame>}
