"""Operational case vNext. Revision ID: 0066_operational_case_vnext"""
from alembic import op
import sqlalchemy as sa
revision="0066_operational_case_vnext"; down_revision="0065_gigi_intelligence"; branch_labels=None; depends_on=None

def common(): return [sa.Column("id",sa.String(64),primary_key=True),sa.Column("public_id",sa.String(36),nullable=False,unique=True),sa.Column("business_number",sa.String(80)),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("plant_id",sa.String(64)),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)]
def upgrade():
    if "platform_case_entity_links" in set(sa.inspect(op.get_bind()).get_table_names()): return
    names={x["name"] for x in sa.inspect(op.get_bind()).get_columns("platform_operational_cases")}
    cols=[sa.Column("summary",sa.Text()),sa.Column("priority_score",sa.Float(),nullable=False,server_default="0"),sa.Column("confidence",sa.Float(),nullable=False,server_default="0"),sa.Column("detected_at",sa.DateTime(timezone=True)),sa.Column("first_possible_detection_at",sa.DateTime(timezone=True)),sa.Column("decision_deadline",sa.DateTime(timezone=True)),sa.Column("expected_impact_at",sa.DateTime(timezone=True)),sa.Column("responsible_team",sa.String(80)),sa.Column("recovery_state",sa.String(32),nullable=False,server_default="PENDING"),sa.Column("current_strategy_id",sa.String(64)),sa.Column("last_evaluated_at",sa.DateTime(timezone=True)),sa.Column("aggregation_key",sa.String(240))]
    for col in cols:
        if col.name not in names: op.add_column("platform_operational_cases",col)
    op.create_table("platform_case_entity_links",*common(),sa.Column("case_id",sa.String(64),sa.ForeignKey("platform_operational_cases.id",ondelete="CASCADE"),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(64),nullable=False),sa.Column("relationship",sa.String(48),nullable=False),sa.Column("importance",sa.Float(),nullable=False,server_default="1"),sa.UniqueConstraint("case_id","entity_type","entity_id","relationship",name="uq_case_entity_link"))
    op.create_table("platform_case_evidence",*common(),sa.Column("case_id",sa.String(64),sa.ForeignKey("platform_operational_cases.id",ondelete="CASCADE"),nullable=False),sa.Column("evidence_type",sa.String(80),nullable=False),sa.Column("source_entity_type",sa.String(80),nullable=False),sa.Column("source_entity_id",sa.String(64),nullable=False),sa.Column("source_event_id",sa.String(64)),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.Column("freshness_state",sa.String(24),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.UniqueConstraint("case_id","source_event_id",name="uq_case_source_event"))
    op.create_table("platform_case_causes",*common(),sa.Column("case_id",sa.String(64),sa.ForeignKey("platform_operational_cases.id",ondelete="CASCADE"),nullable=False),sa.Column("cause_type",sa.String(80),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(64),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("evidence_ids",sa.JSON(),nullable=False))
def downgrade():
    for t in ("platform_case_causes","platform_case_evidence","platform_case_entity_links"): op.drop_table(t)
