"""Feasibility and decisions. Revision ID: 0069_case_decisions"""
from alembic import op
import sqlalchemy as sa
revision="0069_case_decisions"; down_revision="0068_network_constraints"; branch_labels=None; depends_on=None
def c(): return [sa.Column("id",sa.String(64),primary_key=True),sa.Column("public_id",sa.String(36),nullable=False,unique=True),sa.Column("business_number",sa.String(80)),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("plant_id",sa.String(64)),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)]
def upgrade():
 if "platform_feasibility_evaluations" in set(sa.inspect(op.get_bind()).get_table_names()): return
 op.create_table("platform_feasibility_evaluations",*c(),sa.Column("case_id",sa.String(64),sa.ForeignKey("platform_operational_cases.id",ondelete="CASCADE"),nullable=False),sa.Column("strategy_type",sa.String(80),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("estimated_cost",sa.Numeric(20,6)),sa.Column("time_to_effect_hours",sa.Float()),sa.Column("approval_requirements",sa.JSON(),nullable=False),sa.Column("freshness_state",sa.String(24),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("simulation_run_id",sa.String(64)))
 op.create_table("platform_constraint_results",*c(),sa.Column("feasibility_evaluation_id",sa.String(64),sa.ForeignKey("platform_feasibility_evaluations.id",ondelete="CASCADE"),nullable=False),sa.Column("constraint_key",sa.String(120),nullable=False),sa.Column("state",sa.String(24),nullable=False),sa.Column("blocking",sa.Boolean(),nullable=False),sa.Column("explanation",sa.Text(),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False))
 op.create_table("platform_decision_records",*c(),sa.Column("case_id",sa.String(64),sa.ForeignKey("platform_operational_cases.id",ondelete="CASCADE"),nullable=False),sa.Column("baseline_state_snapshot_id",sa.String(64)),sa.Column("planning_run_id",sa.String(64)),sa.Column("decision_deadline",sa.DateTime(timezone=True)),sa.Column("recommended_alternative_id",sa.String(64)),sa.Column("selected_alternative_id",sa.String(64)),sa.Column("decision",sa.String(32),nullable=False),sa.Column("decision_reason",sa.Text()),sa.Column("override_reason",sa.Text()),sa.Column("actor_membership_id",sa.String(64)),sa.Column("approver_membership_id",sa.String(64)),sa.Column("ai_assisted",sa.Boolean(),nullable=False),sa.Column("policy_version",sa.String(80),nullable=False),sa.Column("decided_at",sa.DateTime(timezone=True)))
 op.create_table("platform_decision_alternatives",*c(),sa.Column("decision_record_id",sa.String(64),sa.ForeignKey("platform_decision_records.id",ondelete="CASCADE"),nullable=False),sa.Column("strategy_type",sa.String(80),nullable=False),sa.Column("parameters",sa.JSON(),nullable=False),sa.Column("expected_impact",sa.JSON(),nullable=False),sa.Column("cost",sa.Numeric(20,6)),sa.Column("time_to_effect_hours",sa.Float()),sa.Column("success_probability",sa.Float()),sa.Column("side_effects",sa.JSON(),nullable=False),sa.Column("feasibility_evaluation_id",sa.String(64),sa.ForeignKey("platform_feasibility_evaluations.id"),nullable=False),sa.Column("score",sa.Float(),nullable=False),sa.Column("score_dimensions",sa.JSON(),nullable=False),sa.Column("ranking",sa.Integer(),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("simulation_run_id",sa.String(64)),sa.Column("immutable",sa.Boolean(),nullable=False))
def downgrade():
 for t in ("platform_decision_alternatives","platform_decision_records","platform_constraint_results","platform_feasibility_evaluations"): op.drop_table(t)
