"""Recovery targets and stability verification. Revision ID: 0070_recovery_verification"""
from alembic import op
import sqlalchemy as sa
revision="0070_recovery_verification"; down_revision="0069_case_decisions"; branch_labels=None; depends_on=None
def c(): return [sa.Column("id",sa.String(64),primary_key=True),sa.Column("public_id",sa.String(36),nullable=False,unique=True),sa.Column("business_number",sa.String(80)),sa.Column("tenant_id",sa.String(64),nullable=False),sa.Column("plant_id",sa.String(64)),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False)]
def upgrade():
 if "platform_recovery_targets" in set(sa.inspect(op.get_bind()).get_table_names()): return
 op.create_table("platform_recovery_targets",*c(),sa.Column("case_id",sa.String(64),sa.ForeignKey("platform_operational_cases.id",ondelete="CASCADE"),nullable=False),sa.Column("target_type",sa.String(80),nullable=False),sa.Column("metric",sa.String(80),nullable=False),sa.Column("operator",sa.String(8),nullable=False),sa.Column("threshold",sa.Numeric(20,6),nullable=False),sa.Column("required_duration_seconds",sa.Integer(),nullable=False),sa.Column("required_observation_count",sa.Integer(),nullable=False),sa.Column("freshness_requirement",sa.String(24),nullable=False),sa.Column("baseline",sa.Numeric(20,6)),sa.Column("target",sa.Numeric(20,6),nullable=False))
 op.create_table("platform_recovery_observations",*c(),sa.Column("target_id",sa.String(64),sa.ForeignKey("platform_recovery_targets.id",ondelete="CASCADE"),nullable=False),sa.Column("source_entity",sa.JSON(),nullable=False),sa.Column("observed_value",sa.Numeric(20,6),nullable=False),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("freshness",sa.String(24),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("satisfied",sa.Boolean(),nullable=False))
 op.create_table("platform_recovery_verifications",*c(),sa.Column("case_id",sa.String(64),sa.ForeignKey("platform_operational_cases.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("status",sa.String(32),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("stability_window_start",sa.DateTime(timezone=True)),sa.Column("stability_window_end",sa.DateTime(timezone=True)),sa.Column("evidence_completeness",sa.Float(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("failure_reason",sa.Text()))
def downgrade():
 for t in ("platform_recovery_verifications","platform_recovery_observations","platform_recovery_targets"): op.drop_table(t)
