"use client";
import {useParams} from "next/navigation";
import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {AlertTriangle,ArrowRight,CheckCircle2,Clock3,GitBranch,ShieldCheck,Sparkles} from "lucide-react";
import {ProductShell} from "@/components/platform/ProductShell";
import {getCase,getCaseTimeline,getRecovery,selectCaseDecision} from "@/lib/case-api";
import "../cases.css";

const number=new Intl.NumberFormat("en-US",{maximumFractionDigits:0});
export default function CaseWorkspace(){
 const id=String(useParams().id),cache=useQueryClient();
 const [selection,setSelection]=useState(""),[reason,setReason]=useState(""),[override,setOverride]=useState("");
 const q=useQuery({queryKey:["case",id],queryFn:()=>getCase(id)}),timeline=useQuery({queryKey:["case-timeline",id],queryFn:()=>getCaseTimeline(id)}),recovery=useQuery({queryKey:["case-recovery",id],queryFn:()=>getRecovery(id)});
 const choose=useMutation({mutationFn:(alternativeId:string)=>selectCaseDecision(id,alternativeId,reason,override||undefined),onSuccess:async()=>{setSelection("");await Promise.all([cache.invalidateQueries({queryKey:["case",id]}),cache.invalidateQueries({queryKey:["decision-inbox"]}),cache.invalidateQueries({queryKey:["platform-home"]})])}});
 if(q.isLoading)return <ProductShell module="cases" navigation={[]}><div className="case-state">Loading trusted case context…</div></ProductShell>;
 if(q.error||!q.data)return <ProductShell module="cases" navigation={[]}><div className="case-state error"><AlertTriangle/>Case unavailable</div></ProductShell>;
 const row=q.data;
 return <ProductShell module="cases" navigation={[]} wide><main className="case-workspace">
  <header className="case-hero"><div><p>{row.case_type.replaceAll("_"," ")} · {row.responsible_team}</p><h1>{row.title}</h1><span>{row.summary}</span></div><div><b>{row.severity}</b><small>Recovery state</small><strong>{row.recovery_state.replaceAll("_"," ")}</strong></div></header>
  <section className="case-deadline"><Clock3/><Fact label="Decision deadline" value={row.decision_deadline?new Date(row.decision_deadline).toLocaleString():"Not established"}/><Fact label="Expected impact" value={row.expected_impact_at?new Date(row.expected_impact_at).toLocaleString():"Unknown"}/><Fact label="Grounding" value={`${Math.round(row.confidence*100)}% confidence`}/></section>
  <section className="case-gigi-card"><Sparkles/><div><small>GIGI · CASE COMPANION</small><strong>{row.decision?.alternatives.length??0} recorded recovery options</strong><p>Review evidence, unknown constraints, recommendation and approval boundaries. Recorded options do not establish complete understanding.</p></div><button onClick={()=>window.dispatchEvent(new Event("genuinegigs:open-gigi"))}>Review Gigi&apos;s plan <ArrowRight/></button></section>
  <div className="case-grid"><Panel label="CAUSE → IMPACT" title="What changed and what it threatens" icon={<GitBranch/>}><div className="impact-chain">{row.causes?.map(c=><article key={c.description}><b>Cause</b><strong>{c.description}</strong><small>{Math.round(c.confidence*100)}% confidence</small></article>)}{row.entities.map(e=><article key={`${e.type}-${e.id}`}><b>{e.relationship.replaceAll("_"," ")}</b><strong>{e.label}</strong><small>{e.type.replaceAll("_"," ")}</small></article>)}</div></Panel><Panel label="EXPOSURE" title="Production and customer impact" icon={<AlertTriangle/>}>{row.exposures?.map(e=><article className="exposure" key={e.metric}><strong>{e.delta==null?"Unknown":number.format(e.delta)} {e.unit}</strong><span>{e.metric.replaceAll("_"," ")}</span><details><summary>Calculation and evidence</summary><p>{e.methodology}</p></details></article>)}</Panel></div>
  <Panel label="RECOVERY OPTIONS" title="Compare feasible responses" icon={<ShieldCheck/>}><div className="option-table"><div><span>Option</span><span>Feasibility</span><span>Protected</span><span>Cost</span><span>Time</span><span>Probability</span><span>Score</span><span/></div>{row.decision?.alternatives.map(a=><article className={row.decision?.recommended_alternative_id===a.id?"recommended":""} key={a.id}><span><strong>{a.strategy_type.replaceAll("_"," ")}</strong>{row.decision?.recommended_alternative_id===a.id&&<small>Recommended</small>}</span><b>{a.feasibility.replaceAll("_"," ")}</b><span>{String(a.expected_impact.protected_units??"—")} units</span><span>{a.cost==null?"Unknown":number.format(a.cost)}</span><span>{a.time_to_effect_hours??"—"}h</span><span>{a.success_probability==null?"—":`${Math.round(a.success_probability*100)}%`}</span><strong>{Math.round(a.score)}</strong><button disabled={row.decision?.status!=="PENDING"||a.feasibility==="UNAVAILABLE"} onClick={()=>setSelection(a.id)}>Select <ArrowRight/></button></article>)}</div>{selection&&<form onSubmit={event=>{event.preventDefault();choose.mutate(selection)}} className="case-decision-form"><h3>Record your decision</h3><label>Decision reason<textarea required minLength={3} value={reason} onChange={event=>setReason(event.target.value)}/></label><label>Override or confirmation evidence<textarea required={selection!==row.decision?.recommended_alternative_id||row.decision?.alternatives.find(item=>item.id===selection)?.feasibility==="REQUIRES_CONFIRMATION"} value={override} onChange={event=>setOverride(event.target.value)} placeholder="Required for a non-recommended option or critical unknown"/></label><p>This records a choice and proposes governed work; it does not approve or execute external changes.</p><button type="submit" disabled={choose.isPending}>{choose.isPending?"Recording…":"Record decision"}</button><button type="button" onClick={()=>setSelection("")}>Cancel</button></form>}{choose.error&&<p className="case-error">{choose.error.message}</p>}</Panel>
  <div className="case-grid"><Panel label="ACTION PLAN" title="Governed execution" icon={<CheckCircle2/>}>{row.action_plan?<div className="plan-steps">{row.action_plan.steps.map(step=><article key={step.id}><b>{step.sequence}</b><div><strong>{step.title}</strong><small>{step.owner_team} · {step.status}</small></div><span>Approval required</span></article>)}</div>:<p>Select a feasible option to create approval-bound work.</p>}</Panel><Panel label="RECOVERY MONITORING" title="Stable observed outcome" icon={<ShieldCheck/>}><div className="recovery"><strong>{recovery.data?.status??row.recovery_state}</strong><p>Execution does not close this case. Fresh operational evidence is required.</p>{recovery.data?.targets.map(t=><article key={t.id}><small>{t.metric.replaceAll("_"," ")} {t.operator} {t.threshold} · {t.required_observation_count} distinct cycles</small>{t.observations.map(observation=><span key={observation.id}>{new Date(observation.observed_at).toLocaleString()} · {observation.value} · {observation.freshness} · {observation.satisfied?"target met":"not met"}</span>)}</article>)}{recovery.data?.verification?.failure_reason&&<p>{recovery.data.verification.failure_reason}</p>}</div></Panel></div>
  <Panel label="CASE TIMELINE" title="Changes and evidence" icon={<Clock3/>}><div className="timeline">{timeline.data?.map((event,index)=><article key={`${event.type}-${index}`}><i/><span>{new Date(event.at).toLocaleString()}</span><strong>{event.title}</strong><small>Audited operational evidence</small></article>)}</div></Panel>
 </main></ProductShell>;
}
function Fact({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
function Panel({label,title,icon,children}:{label:string;title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="case-panel"><header>{icon}<div><small>{label}</small><h2>{title}</h2></div></header>{children}</section>}
