"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, BellRing, Bot, BriefcaseBusiness, Check, Clock3, ExternalLink, LoaderCircle, MessageSquare, MessageSquarePlus, Radar, ShieldCheck, Sparkles, X } from "lucide-react";
import { commandGigiInsight,createGigiConversation,getGigiBrief,getGigiCommitments,getGigiInsights,getGigiMessages,listGigiConversations,planGigiCase,sendGigiMessage,type GigiConversation,type GigiMessage,type GigiPageContext } from "@/lib/api";

type LocalMessage=Pick<GigiMessage,"id"|"type"|"content"|"citations">&{uncertainties?:string[]};
type View="attention"|"brief"|"plan"|"commitments"|"ask";

export function GigiPanel({open,onClose,context,initialView}:{open:boolean;onClose:()=>void;context:GigiPageContext;initialView?:View}){
 const cache=useQueryClient(),[view,setView]=useState<View>("attention"),[conversation,setConversation]=useState<GigiConversation|null>(null),[messages,setMessages]=useState<LocalMessage[]>([]),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const end=useRef<HTMLDivElement>(null),routeCase=context.route?.match(/^\/cases\/([^/?]+)/)?.[1],caseId=context.entity_type==="operational_case"?context.entity_id:routeCase;
 const loadingConversation=useRef(false);
 const insights=useQuery({queryKey:["gigi-insights"],queryFn:getGigiInsights,enabled:open,refetchInterval:30000});
 const brief=useQuery({queryKey:["gigi-brief"],queryFn:getGigiBrief,enabled:open&&view==="brief",retry:false});
 const commitments=useQuery({queryKey:["gigi-commitments"],queryFn:getGigiCommitments,enabled:open&&view==="commitments",retry:false});
 const plan=useQuery({queryKey:["gigi-case-plan",caseId],queryFn:()=>planGigiCase(caseId!),enabled:open&&view==="plan"&&Boolean(caseId),retry:false});
 const active=useMemo(()=>insights.data?.filter(row=>!["ACKNOWLEDGED","DISMISSED","RESOLVED"].includes(row.delivery_state)&&!row.acknowledged_at&&!row.dismissed_at&&(!row.snoozed_until||new Date(row.snoozed_until).getTime()<=Date.now()))??[],[insights.data]);
 const currentQuery=view==="attention"?insights:view==="brief"?brief:view==="plan"?plan:view==="commitments"?commitments:null;
 useEffect(()=>{if(open)setView(initialView??(caseId?"plan":"attention"))},[open,caseId,initialView]);
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[open,onClose]);
 useEffect(()=>{if(!open||view!=="ask"||conversation||loadingConversation.current)return;loadingConversation.current=true;void listGigiConversations().then(async rows=>{const row=rows.find(item=>item.context?.route===context.route&&item.context?.entity_id===context.entity_id)??await createGigiConversation(context);const history=await getGigiMessages(row.id);setConversation(row);setMessages(history)}).catch(e=>setError(e instanceof Error?e.message:"Gigi is unavailable")).finally(()=>{loadingConversation.current=false})},[open,view,conversation,context]);
 useEffect(()=>{const node=end.current;if(node&&typeof node.scrollIntoView==="function")node.scrollIntoView({behavior:"smooth"})},[messages,busy]);
 async function command(id:string,action:"acknowledge"|"snooze"|"dismiss"){try{await commandGigiInsight(id,action);await cache.invalidateQueries({queryKey:["gigi-insights"]});setError("")}catch(e){setError(e instanceof Error?e.message:"Could not update insight. Please retry.")}}
 async function send(){if(!draft.trim()||busy||loadingConversation.current)return;const question=draft.trim(),localId=crypto.randomUUID();setBusy(true);setError("");try{const row=conversation??await createGigiConversation(context);setConversation(row);setDraft("");setMessages(old=>[...old,{id:localId,type:"user",content:question,citations:[]}]);const result=await sendGigiMessage(row.id,question,context);setMessages(old=>[...old,{id:result.message_id,type:"assistant",content:result.response.answer,citations:result.response.evidence,uncertainties:result.response.uncertainties}])}catch(e){setDraft(question);setMessages(old=>old.filter(item=>item.id!==localId));setError(`${e instanceof Error?e.message:"Gigi could not investigate"}. Your draft has been restored; check the conversation before retrying.`)}finally{setBusy(false)}}
 function submit(e:FormEvent){e.preventDefault();void send()}
 async function fresh(){try{const row=await createGigiConversation(context);setConversation(row);setMessages([]);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not create conversation")}}
 if(!open)return null;
 const views:Array<[View,string,typeof Radar]>=[["attention","Attention",Radar],["brief","Brief",Sparkles],["plan","Plan",ShieldCheck],["commitments","Commitments",BriefcaseBusiness],["ask","Ask",MessageSquare]];
 return <><button className="gigi-scrim" onClick={onClose} aria-label="Close Gigi"/><aside className="gigi-panel gigi-companion-panel" aria-label="Gigi proactive manufacturing companion">
  <header><div className="gigi-mark"><Sparkles/></div><div><strong>Gigi</strong><span>Active manufacturing companion</span></div><i className="gigi-watch-state"><Radar/> watching {context.module??"factory"}</i><button onClick={onClose} aria-label="Close"><X/></button></header>
  <nav className="gigi-companion-nav">{views.map(([key,label,Icon])=><button key={key} className={view===key?"active":""} disabled={key==="plan"&&!caseId} onClick={()=>setView(key)}><Icon/>{label}{key==="attention"&&active.length?<b>{active.length}</b>:null}</button>)}</nav>
  <div className="gigi-context"><ShieldCheck/><span>{caseId?`Recovery case ${caseId}`:`${context.module??"factory"} context`}</span><i>Evidence governed</i></div>
  <section className="gigi-companion-body">
   {currentQuery?.isError&&<div role="alert" className="gigi-error"><strong>Operational context unavailable</strong><p>Gigi cannot establish the current state. A failed request does not mean the factory is stable.</p><button onClick={()=>void currentQuery.refetch()}>Retry</button></div>}
   {view==="attention"&&!currentQuery?.isError&&<div className="gigi-attention"><Intro label="WHAT I AM WATCHING" title={active.length?`${active.length} item${active.length===1?"":"s"} may need you`:"No intervention needed"}>Gigi monitors deadlines, case state and recovery evidence while you work.</Intro>{insights.isLoading?<Loading text="Reviewing operational state…"/>:active.length?active.map(item=><article className={item.severity.toLowerCase()} key={item.id}><div><BellRing/><span><small>{item.category.replaceAll("_"," ")}</small><strong>{item.title.replace(/^Gigi noticed:\s*/,"")}</strong></span><b>{item.severity}</b></div><p>{item.summary}</p><details><summary>Evidence and monitoring</summary><span>{item.evidence.length} evidence reference{item.evidence.length===1?"":"s"}{item.next_evaluation_at?` · next check ${new Date(item.next_evaluation_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:""}</span></details><footer>{item.case_id&&<Link href={`/cases/${item.case_id}`}>Open case <ArrowRight/></Link>}<button onClick={()=>command(item.id,"acknowledge")}><Check/> Acknowledge</button><button onClick={()=>command(item.id,"snooze")}><Clock3/> Snooze</button><button onClick={()=>command(item.id,"dismiss")}><X/> Dismiss</button></footer></article>):<Empty/>}</div>}
   {view==="brief"&&!currentQuery?.isError&&<div className="gigi-brief"><Intro label="ROLE-AWARE BRIEFING" title={brief.data?.title??"Preparing your operational brief"}>Cases, decisions, commitments and outcomes ordered by consequence and deadline.</Intro>{brief.isLoading?<Loading text="Building the brief from current evidence…"/>:brief.data?.items.length?brief.data.items.map(item=><Link href={item.href.replace("/platform/cases/","/cases/")} key={`${item.kind}-${item.id}`}><i className={item.severity}/><div><small>{item.kind}</small><strong>{item.title}</strong><span>{item.evidence_ref}</span></div><ArrowRight/></Link>):<Empty/>}</div>}
   {view==="plan"&&!currentQuery?.isError&&<div className="gigi-plan"><Intro label="STRUCTURED RECOVERY SIDECAR" title={plan.data?.understood_problem??"Understanding this case"}>Gigi assembles deterministic options and governed work; it does not approve operational truth.</Intro>{plan.isLoading?<Loading text="Gathering evidence and evaluated strategies…"/>:<><section><h3>Recommended response</h3>{plan.data?.recommended_plan?<PlanCard row={plan.data.recommended_plan}/>:<p>No recommendation is available until constraints are sufficiently known.</p>}</section><section><h3>Options already evaluated</h3><div className="gigi-plan-options">{plan.data?.strategies_evaluated.map((row,i)=><PlanCard row={row} key={String(row.id??i)}/>)}</div></section><section className="gigi-guardrails"><ShieldCheck/><div><strong>Human control remains active</strong>{plan.data?.guardrails.map(rule=><small key={rule}>{rule}</small>)}</div></section></>}</div>}
   {view==="commitments"&&!currentQuery?.isError&&<div className="gigi-commitments"><Intro label="DURABLE FOLLOW-THROUGH" title="Promises I am monitoring">Persisted operational commitments—not conversational memory.</Intro>{commitments.isLoading?<Loading text="Checking owners, due times and evidence…"/>:commitments.data?.length?commitments.data.map(item=><article key={item.id}><Clock3/><div><small>{item.dependency_state??"OPERATIONAL"} · {item.status}</small><strong>{item.deliverable}</strong><span>Due {new Date(item.due_at).toLocaleString()}</span>{item.evidence_requirement&&<p>Completion proof: {item.evidence_requirement}</p>}</div>{item.case_id&&<Link href={`/cases/${item.case_id}`}>Case <ArrowRight/></Link>}</article>):<Empty/>}</div>}
   {view==="ask"&&<div className="gigi-ask"><div className="gigi-thread">{!messages.length&&!busy&&<div className="gigi-empty"><Bot/><h2>Ask a follow-up</h2><p>Conversation supports the companion workflow; current factory evidence remains authoritative.</p>{["What changed since the last plan?","Explain the highest-impact case","What is waiting on another team?"].map(p=><button type="button" key={p} onClick={()=>setDraft(p)}>{p}<ArrowRight/></button>)}</div>}{messages.map(m=><article key={m.id} className={`gigi-message ${m.type}`}><span>{m.type==="user"?"You":"Gigi"}</span><p>{m.content}</p>{Boolean(m.citations?.length)&&<div className="gigi-evidence"><strong>Evidence</strong>{m.citations.map(c=><small key={c.ref}>{c.label}{c.freshness?` · ${c.freshness}`:""}</small>)}</div>}{m.uncertainties?.map(u=><small className="gigi-warning" key={u}>{u}</small>)}</article>)}{busy&&<Loading text="Investigating authorized records…"/>}<div ref={end}/></div><form onSubmit={submit}><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}} placeholder="Ask a follow-up about this context…" rows={3}/><div><small>Enter to send · Shift+Enter for a new line</small><button type="submit" disabled={busy||!draft.trim()} aria-label="Send message"><ArrowRight/></button></div></form></div>}
   {error&&<p className="gigi-error">{error}</p>}
  </section>
  <footer className="gigi-companion-footer"><span><Radar/> Monitoring continues when closed.</span>{view==="ask"&&<button onClick={fresh}><MessageSquarePlus/> New conversation</button>}<Link href="/gigi">Companion workspace <ExternalLink/></Link></footer>
 </aside></>;
}
function Intro({label,title,children}:{label:string;title:string;children:React.ReactNode}){return <header className="gigi-view-intro"><small>{label}</small><h2>{title}</h2><p>{children}</p></header>}
function Loading({text}:{text:string}){return <div className="gigi-thinking"><LoaderCircle/><span>{text}</span></div>}
function Empty(){return <div className="gigi-companion-empty"><Check/><strong>No items returned</strong><p>Gigi will surface a change when evidence or deadlines require attention.</p></div>}
function PlanCard({row}:{row:Record<string,unknown>}){const name=String(row.strategy_type??row.title??"Recovery option").replaceAll("_"," "),score=typeof row.score==="number"?Math.round(row.score):null;return <article><div><strong>{name}</strong>{score!=null&&<b>{score}</b>}</div><span>{String(row.feasibility??"requires confirmation").replaceAll("_"," ")}</span>{row.time_to_effect_hours!=null&&<small>Time to effect: {String(row.time_to_effect_hours)}h</small>}{row.success_probability!=null&&<small>Success probability: {Math.round(Number(row.success_probability)*100)}%</small>}</article>}
