from __future__ import annotations

import hashlib
import json
from datetime import datetime, timedelta, timezone
from io import BytesIO
from typing import Any

from fastapi import HTTPException
from sqlalchemy.orm import Session

from app import agent_service, procurement_policy
from app.core.config import get_settings
from app.core.permissions import (
    ADMIN, PLANT_MANAGER, PURCHASE_EXECUTIVE, PURCHASE_MANAGER,
    require_role, require_workspace_capability,
)
from app.db import models
from app.domains import workflows
from app.storage import object_storage


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def require_procurement_v2(db: Session, user: models.User) -> None:
    flag = db.query(models.TenantFeatureFlag).filter_by(
        tenant_id=user.tenant_id, key="procurement_v2"
    ).first()
    tenant = db.get(models.Tenant, user.tenant_id)
    enabled = flag.enabled if flag is not None else bool(
        tenant and (tenant.feature_flags or {}).get("procurement_v2")
    )
    if not enabled:
        raise HTTPException(status_code=404, detail="Procurement V2 is not enabled for this workspace")


def _paragraph(value: Any, style: Any) -> Any:
    from reportlab.platypus import Paragraph
    text = str(value if value not in (None, "") else "-")
    return Paragraph(text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"), style)


def _render_pdf(
    title: str,
    subtitle: str,
    metadata: list[tuple[str, Any]],
    headers: list[str],
    rows: list[list[Any]],
    notes: list[str],
    draft: bool,
) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.pdfgen.canvas import Canvas
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    class StableCanvas(Canvas):
        def __init__(self, *args: Any, **kwargs: Any):
            kwargs["invariant"] = 1
            super().__init__(*args, **kwargs)

    buffer = BytesIO()
    page_size = landscape(A4) if len(headers) > 6 else A4
    document = SimpleDocTemplate(
        buffer, pagesize=page_size, leftMargin=16 * mm, rightMargin=16 * mm,
        topMargin=15 * mm, bottomMargin=16 * mm,
        title=title, author="GenuineGigs",
    )
    styles = getSampleStyleSheet()
    styles["Title"].fontName = "Helvetica-Bold"
    styles["Title"].fontSize = 17
    styles["BodyText"].fontSize = 8.5
    styles["BodyText"].leading = 11
    story: list[Any] = [
        Paragraph(title, styles["Title"]),
        Paragraph(subtitle, styles["BodyText"]),
        Spacer(1, 7 * mm),
    ]
    meta_rows = [[_paragraph(label, styles["BodyText"]), _paragraph(value, styles["BodyText"])] for label, value in metadata]
    meta_table = Table(meta_rows, colWidths=[42 * mm, None], hAlign="LEFT")
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#d5d0c5")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.extend([meta_table, Spacer(1, 7 * mm)])
    data = [[_paragraph(value, styles["BodyText"]) for value in headers]]
    data.extend([[_paragraph(value, styles["BodyText"]) for value in row] for row in rows])
    table = Table(data, repeatRows=1, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e9e5dc")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#bcb5a7")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.extend([table, Spacer(1, 7 * mm)])
    for note in notes:
        story.append(Paragraph(note, styles["BodyText"]))

    def decorate(canvas: Canvas, doc: Any) -> None:
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#5d5a54"))
        canvas.drawString(16 * mm, 8 * mm, f"Generated by GenuineGigs | Page {doc.page}")
        if draft:
            canvas.setFillColor(colors.Color(0.55, 0.15, 0.12, alpha=0.18))
            canvas.setFont("Helvetica-Bold", 58)
            canvas.translate(page_size[0] / 2, page_size[1] / 2)
            canvas.rotate(28)
            canvas.drawCentredString(0, 0, "DRAFT")
        canvas.restoreState()

    document.build(story, onFirstPage=decorate, onLaterPages=decorate, canvasmaker=StableCanvas)
    return buffer.getvalue()


def _artifact_payload(db: Session, user: models.User, artifact_type: str, entity_id: str) -> dict[str, Any]:
    company = db.query(models.Company).filter_by(tenant_id=user.tenant_id).first()
    plant = db.query(models.Plant).filter_by(id=user.plant_id, tenant_id=user.tenant_id).first()
    base = {"company": company.name if company else "Company", "plant": plant.name if plant else user.plant_id}
    if artifact_type == "rfq":
        rfq = workflows.get_scoped_or_404(db, models.RFQ, user, entity_id, "RFQ")
        lines = workflows.user_scope_query(db, models.RFQLine, user).filter_by(rfq_id=rfq.id).all()
        suppliers = workflows.user_scope_query(db, models.Supplier, user).filter(models.Supplier.id.in_(rfq.supplier_ids or [""])).all()
        return {
            **base, "entity": rfq, "number": rfq.business_number or rfq.id,
            "metadata": [("Company / plant", f"{base['company']} / {base['plant']}"), ("RFQ", rfq.business_number or rfq.id),
                         ("Quotation deadline", rfq.deadline), ("Invited suppliers", ", ".join(row.name for row in suppliers))],
            "headers": ["Material", "Description", "Quantity", "UOM", "Need by", "Certificates"],
            "rows": [[db.get(models.Item, line.item_id).name if db.get(models.Item, line.item_id) else line.item_id,
                      line.description, line.quantity, line.uom, line.need_by_date, ", ".join(line.required_certificates or [])] for line in lines],
            "notes": ["Please quote taxes, freight, packaging, payment terms, lead time, delivery date, MOQ, certificates, and all deviations.",
                      "Submit the signed quotation through the secure supplier portal link supplied with this RFQ."],
        }
    if artifact_type == "comparison":
        comparison = workflows.get_scoped_or_404(db, models.BidComparison, user, entity_id, "Comparison")
        rfq = workflows.get_scoped_or_404(db, models.RFQ, user, comparison.rfq_id, "RFQ")
        return {
            **base, "entity": comparison, "number": comparison.business_number or comparison.id,
            "metadata": [("Company / plant", f"{base['company']} / {base['plant']}"), ("RFQ", rfq.business_number or rfq.id),
                         ("Comparison version", comparison.comparison_version), ("Recommendation", comparison.recommendation_rationale)],
            "headers": ["Supplier", "Quote", "Landed unit cost", "Total landed cost", "Delivery", "Technical", "Quality", "Decision / reasons"],
            "rows": [[row.get("supplier_name"), row.get("quote_id"), row.get("net_landed_unit_cost"),
                      row.get("total_net_landed_cost"), "Compliant" if row.get("delivery_compliant") else "Deviation",
                      "Compliant" if row.get("technical_compliant") else "Deviation", row.get("quality_score"),
                      f"{row.get('recommendation', '')}: {', '.join(row.get('reasons') or [])}"] for row in comparison.rows],
            "notes": ["This version is approval-bound. Commercial data cannot be edited by approvers."],
        }
    if artifact_type == "po":
        po = workflows.get_scoped_or_404(db, models.PODraft, user, entity_id, "Purchase order")
        supplier = workflows.get_scoped_or_404(db, models.Supplier, user, po.supplier_id, "Supplier")
        award = workflows.get_scoped_or_404(db, models.AwardDecision, user, po.award_id, "Award")
        lines = workflows.user_scope_query(db, models.PODraftLine, user).filter_by(po_draft_id=po.id).all()
        total = sum(line.quantity * line.unit_price * (1 + line.gst_rate / 100) for line in lines)
        return {
            **base, "entity": po, "number": po.business_number or po.id,
            "metadata": [("Company / plant", f"{base['company']} / {base['plant']}"), ("Purchase order", po.business_number or po.id),
                         ("Supplier", supplier.name), ("RFQ / award", f"{award.rfq_id} / {award.business_number or award.id}"),
                         ("Ship to", base["plant"]), ("Currency / terms", f"{po.currency} / {po.payment_terms}"), ("Order total", f"{total:.2f}")],
            "headers": ["Material", "Quantity", "UOM", "Unit price", "Tax %", "Need by", "Line total"],
            "rows": [[db.get(models.Item, line.item_id).name if db.get(models.Item, line.item_id) else line.item_id,
                      line.quantity, line.uom, f"{line.unit_price:.2f}", line.gst_rate, line.need_by_date,
                      f"{line.quantity * line.unit_price * (1 + line.gst_rate / 100):.2f}"] for line in lines],
            "notes": ["Supplier dispatch and ERP posting are separate controlled actions.", "Quality and delivery conditions follow the approved RFQ and quotation."],
        }
    raise HTTPException(status_code=422, detail="Unsupported artifact type")


def generate_artifact(
    db: Session, user: models.User, artifact_type: str, entity_id: str, *, final: bool
) -> models.GeneratedArtifact:
    require_procurement_v2(db, user)
    # The application session uses autoflush=False. Persist pending RFQ/PO lines
    # before building the immutable document snapshot.
    db.flush()
    payload = _artifact_payload(db, user, artifact_type, entity_id)
    if final and artifact_type == "po" and not payload["rows"]:
        raise HTTPException(
            status_code=409,
            detail="A purchase order cannot be finalized without commercial lines",
        )
    snapshot = json.dumps({key: value for key, value in payload.items() if key != "entity"}, sort_keys=True, default=str)
    snapshot_hash = hashlib.sha256(snapshot.encode()).hexdigest()
    latest = workflows.user_scope_query(db, models.GeneratedArtifact, user).filter_by(
        artifact_type=artifact_type, entity_type=artifact_type, entity_id=entity_id
    ).order_by(models.GeneratedArtifact.artifact_version.desc()).first()
    if final and latest and latest.status == "final" and latest.source_snapshot_hash == snapshot_hash:
        return latest
    version = (latest.artifact_version if latest else 0) + 1
    pdf = _render_pdf(
        f"{artifact_type.upper()} {payload['number']}",
        "Controlled procurement document" if final else "Preview for review; this document is not issued",
        payload["metadata"], payload["headers"], payload["rows"], payload["notes"], not final,
    )
    checksum = hashlib.sha256(pdf).hexdigest()
    settings = get_settings()
    key = f"{user.tenant_id}/{user.plant_id}/artifacts/{artifact_type}/{entity_id}/v{version}-{checksum[:12]}.pdf"
    object_storage.put_file(settings.object_storage_evidence_bucket, key, BytesIO(pdf), "application/pdf")
    document = models.Document(
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        filename=f"{artifact_type}-{payload['number']}-v{version}.pdf", content_type="application/pdf",
        size_bytes=len(pdf), storage_key=key, storage_bucket=settings.object_storage_evidence_bucket,
        checksum_sha256=checksum, status="generated_final" if final else "generated_draft",
        validation_errors=[], linked_entity_type=artifact_type, linked_entity_id=entity_id,
        uploaded_by_user_id=user.id,
    )
    db.add(document)
    db.flush()
    artifact = models.GeneratedArtifact(
        tenant_id=user.tenant_id, plant_id=user.plant_id, artifact_type=artifact_type,
        entity_type=artifact_type, entity_id=entity_id, artifact_version=version,
        document_id=document.id, status="final" if final else "draft",
        source_snapshot_hash=snapshot_hash, generated_by_user_id=user.id,
        finalized_at=utcnow() if final else None,
    )
    db.add(artifact)
    db.flush()
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name, f"{artifact_type}.artifact.{'finalized' if final else 'previewed'}",
        artifact_type, entity_id, actor_user_id=user.id,
        meta={"artifact_id": artifact.id, "version": version, "checksum": checksum},
    )
    return artifact


def artifact_record(db: Session, user: models.User, artifact: models.GeneratedArtifact) -> dict[str, Any]:
    document = workflows.get_scoped_or_404(db, models.Document, user, artifact.document_id, "Artifact document")
    return {
        **workflows.record_to_dict(artifact),
        "filename": document.filename,
        "checksum_sha256": document.checksum_sha256,
        "download_url": f"/documents/{document.id}/download-url",
    }


def list_artifacts(db: Session, user: models.User, artifact_type: str, entity_id: str) -> list[dict[str, Any]]:
    require_procurement_v2(db, user)
    records = workflows.user_scope_query(db, models.GeneratedArtifact, user).filter_by(
        artifact_type=artifact_type, entity_type=artifact_type, entity_id=entity_id
    ).order_by(models.GeneratedArtifact.artifact_version.desc()).all()
    return [artifact_record(db, user, row) for row in records]


def create_material_request(
    db: Session, user: models.User, item_code: str, description: str,
    uom: str, specification: str, reason: str,
) -> models.MaterialMasterRequest:
    require_procurement_v2(db, user)
    require_role(user, PLANT_MANAGER, PURCHASE_MANAGER, PURCHASE_EXECUTIVE, ADMIN)
    duplicate = workflows.user_scope_query(db, models.Item, user).filter(
        models.Item.code == item_code
    ).first()
    if duplicate:
        raise HTTPException(status_code=409, detail="An approved material already uses this item code")
    request = models.MaterialMasterRequest(
        tenant_id=user.tenant_id, plant_id=user.plant_id, requested_name=description,
        requested_code=item_code, uom=uom, specification=specification, reason=reason,
        status="pending", requested_by_user_id=user.id,
    )
    db.add(request)
    db.flush()
    admin = db.query(models.User).filter_by(
        tenant_id=user.tenant_id, plant_id=user.plant_id, role=ADMIN, is_active=True
    ).first()
    db.add(models.Task(
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        title=f"Review new material {item_code}", owner_role=ADMIN,
        owner_user_id=admin.id if admin else None, status="pending_approval",
        severity="action", entity_type="material_master_request", entity_id=request.id,
        due_at=utcnow() + timedelta(days=1),
    ))
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name, "material_master.requested",
        "material_master_request", request.id, actor_user_id=user.id,
    )
    return request


def decide_material_request(
    db: Session, user: models.User, request_id: str, decision: str, reason: str
) -> models.MaterialMasterRequest:
    require_procurement_v2(db, user)
    if user.role != ADMIN:
        require_workspace_capability(db, user, 'workspace.manage_master_data')
    request = workflows.get_scoped_or_404(
        db, models.MaterialMasterRequest, user, request_id, "Material master request"
    )
    if request.status != "pending":
        raise HTTPException(status_code=409, detail="This material request has already been decided")
    request.status = "approved" if decision == "approve" else "rejected"
    request.decided_by_user_id = user.id
    request.decided_at = utcnow()
    request.decision_reason = reason
    if decision == "approve":
        item = models.Item(
            tenant_id=user.tenant_id, plant_id=user.plant_id,
            code=request.requested_code or f"ITEM-{request.id[:8]}",
            name=request.requested_name, uom_id=request.uom,
            erp_item_code=request.requested_code or f"PENDING-{request.id[:8]}",
        )
        db.add(item)
        db.flush()
        request.resulting_item_id = item.id
        db.add(models.ItemSpecification(
            tenant_id=user.tenant_id, plant_id=user.plant_id, item_id=item.id,
            description=request.specification, required_certificates=[], inspection_required=True,
        ))
    requester_membership = db.query(models.WorkspaceMembership).filter_by(
        tenant_id=user.tenant_id, user_id=request.requested_by_user_id, status="active",
    ).first()
    db.add(models.Notification(
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        user_id=request.requested_by_user_id,
        membership_id=requester_membership.id if requester_membership else None,
        title=f"Material request {request.status}",
        body=(
            f"{request.requested_name} was approved and is ready for requirement creation."
            if request.status == "approved"
            else f"{request.requested_name} was rejected: {reason}"
        ),
        status="unread", category="material_master_decision",
        severity="info" if request.status == "approved" else "action",
        linked_entity_type="material_master_request", linked_entity_id=request.id,
        navigation_target="/procurement",
    ))
    workflows.complete_tasks_for_entity(db, user, "material_master_request", request.id)
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name, f"material_master.{request.status}",
        "material_master_request", request.id, actor_user_id=user.id,
        meta={"reason": reason, "resulting_item_id": request.resulting_item_id},
    )
    return request


def create_supplier_master(
    db: Session, user: models.User, *, name: str, vendor_id: str,
    contact_name: str, email: str, phone: str, site_name: str,
    currency: str, payment_terms: str, item_ids: list[str],
) -> models.Supplier:
    require_procurement_v2(db, user)
    if user.role != ADMIN:
        require_workspace_capability(db, user, 'workspace.manage_master_data')
    existing = workflows.user_scope_query(db, models.Supplier, user).filter(
        models.Supplier.erp_vendor_id == vendor_id
    ).first()
    if existing:
        raise HTTPException(status_code=409, detail="Supplier vendor ID already exists")
    items = [
        workflows.get_scoped_or_404(db, models.Item, user, item_id, "Item")
        for item_id in item_ids
    ]
    compliance_required = workflows.user_scope_query(db, models.SupplierComplianceRequirement, user).filter_by(active=True, mandatory=True).count() > 0
    supplier = models.Supplier(
        id=workflows.next_id(db, models.Supplier, "SUP"), tenant_id=user.tenant_id,
        plant_id=user.plant_id, name=name.strip(), status="conditional" if compliance_required else "approved",
        quality_score=50, delivery_score=50, erp_vendor_id=vendor_id.strip(),
    )
    db.add(supplier)
    db.flush()
    db.add(models.SupplierContact(
        id=workflows.next_id(db, models.SupplierContact, "SCON"),
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        supplier_id=supplier.id, name=contact_name.strip(),
        email=email.lower().strip(), phone=phone.strip(),
    ))
    db.add(models.SupplierSite(
        id=workflows.next_id(db, models.SupplierSite, "SSITE"),
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        supplier_id=supplier.id, name=site_name.strip(),
        currency=currency.upper().strip(), payment_terms=payment_terms.strip(),
    ))
    for item in items:
        db.add(models.SupplierItemCapability(
            id=workflows.next_id(db, models.SupplierItemCapability, "SIC"),
            tenant_id=user.tenant_id, plant_id=user.plant_id,
            supplier_id=supplier.id, item_id=item.id, approved=True,
            notes="Approved by workspace administrator",
        ))
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name,
        "supplier_master.created", "supplier", supplier.id,
        actor_user_id=user.id, meta={"vendor_id": vendor_id, "item_ids": item_ids},
    )
    return supplier


def assign_suppliers_to_material(
    db: Session, user: models.User, *, item_id: str,
    supplier_ids: list[str], notes: str,
) -> list[models.SupplierItemCapability]:
    """Idempotently approve supplier capabilities for one material."""
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_EXECUTIVE, ADMIN)
    item = workflows.get_scoped_or_404(db, models.Item, user, item_id, "Item")
    unique_supplier_ids = list(dict.fromkeys(supplier_ids))
    suppliers = [
        workflows.get_scoped_or_404(db, models.Supplier, user, supplier_id, "Supplier")
        for supplier_id in unique_supplier_ids
    ]
    capabilities: list[models.SupplierItemCapability] = []
    for supplier in suppliers:
        capability = workflows.user_scope_query(
            db, models.SupplierItemCapability, user,
        ).filter_by(supplier_id=supplier.id, item_id=item.id).first()
        if capability is None:
            capability = models.SupplierItemCapability(
                id=workflows.next_id(db, models.SupplierItemCapability, "SIC"),
                tenant_id=user.tenant_id, plant_id=user.plant_id,
                supplier_id=supplier.id, item_id=item.id,
                approved=True, notes=notes.strip(),
            )
            db.add(capability)
        else:
            capability.approved = True
            capability.notes = notes.strip()
        capabilities.append(capability)
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name,
        "supplier_capability.assigned", "item", item.id,
        actor_user_id=user.id,
        meta={"item_id": item.id, "supplier_ids": unique_supplier_ids, "notes": notes},
    )
    db.flush()
    return capabilities


def create_supplier_contact(
    db: Session, user: models.User, *, supplier_id: str,
    name: str, email: str, phone: str = "",
) -> models.SupplierContact:
    """Add an operational delivery contact to an existing supplier master."""
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_MANAGER, ADMIN)
    supplier = workflows.get_scoped_or_404(db, models.Supplier, user, supplier_id, "Supplier")
    normalized_email = email.lower().strip()
    existing = workflows.user_scope_query(db, models.SupplierContact, user).filter(
        models.SupplierContact.supplier_id == supplier.id,
        models.SupplierContact.email == normalized_email,
    ).first()
    if existing:
        return existing
    contact = models.SupplierContact(
        id=workflows.next_id(db, models.SupplierContact, "SCON"),
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        supplier_id=supplier.id, name=name.strip(),
        email=normalized_email, phone=phone.strip(),
    )
    db.add(contact)
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name,
        "supplier.contact_added", "supplier", supplier.id,
        actor_user_id=user.id,
        meta={"contact_id": contact.id, "email": normalized_email},
    )
    return contact


def create_compliance_requirement(
    db: Session, user: models.User, certificate_type: str, description: str,
    item_id: str | None, mandatory: bool,
) -> models.SupplierComplianceRequirement:
    require_procurement_v2(db, user)
    if user.role != ADMIN:
        require_workspace_capability(db, user, "workspace.manage_master_data")
    if item_id:
        workflows.get_scoped_or_404(db, models.Item, user, item_id, "Material")
    existing = workflows.user_scope_query(db, models.SupplierComplianceRequirement, user).filter_by(
        certificate_type=certificate_type.strip(), item_id=item_id,
    ).first()
    if existing:
        raise HTTPException(status_code=409, detail="This supplier compliance requirement already exists")
    requirement = models.SupplierComplianceRequirement(
        business_number=workflows.next_business_number(db, "SCR", user),
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        certificate_type=certificate_type.strip(), description=description.strip(),
        item_id=item_id, mandatory=mandatory, active=True,
    )
    db.add(requirement)
    db.flush()
    workflows.create_audit(db, user.tenant_id, user.plant_id, user.name, "supplier_compliance.requirement_created", "supplier_compliance_requirement", requirement.id, actor_user_id=user.id)
    return requirement


def submit_supplier_certificate(
    db: Session, user: models.User, supplier_id: str, certificate_type: str,
    certificate_number: str, document_id: str | None, valid_from: str, expires_on: str,
) -> models.SupplierCertificate:
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_MANAGER, ADMIN)
    supplier = workflows.get_scoped_or_404(db, models.Supplier, user, supplier_id, "Supplier")
    try:
        expiry = datetime.fromisoformat(expires_on).date()
        start = datetime.fromisoformat(valid_from).date() if valid_from else None
    except ValueError as exc:
        raise HTTPException(status_code=422, detail="Certificate dates must use YYYY-MM-DD") from exc
    if start and start > expiry:
        raise HTTPException(status_code=422, detail="Certificate expiry must be after its valid-from date")
    if document_id:
        workflows.get_scoped_or_404(db, models.Document, user, document_id, "Certificate document")
    previous = workflows.user_scope_query(db, models.SupplierCertificate, user).filter_by(
        supplier_id=supplier.id, certificate_type=certificate_type.strip(), status="verified",
    ).all()
    for row in previous:
        row.status = "superseded"
    certificate = models.SupplierCertificate(
        business_number=workflows.next_business_number(db, "SCERT", user),
        tenant_id=user.tenant_id, plant_id=user.plant_id, supplier_id=supplier.id,
        certificate_type=certificate_type.strip(), certificate_number=certificate_number.strip(),
        document_id=document_id, valid_from=valid_from, expires_on=expires_on,
        status="pending_review",
    )
    db.add(certificate)
    db.flush()
    supplier.status = "conditional" if supplier.status != "blocked" else supplier.status
    reviewer, reviewer_user = _membership_for_role(db, user, PURCHASE_MANAGER)
    db.add(models.Task(
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        title=f"Review {certificate.certificate_type} evidence for {supplier.name}",
        owner_role=PURCHASE_MANAGER, owner_user_id=reviewer_user.id,
        owner_membership_id=reviewer.id, status="pending_approval", severity="action",
        entity_type="supplier_certificate", entity_id=certificate.id,
        due_at=utcnow() + timedelta(days=1),
        semantic_key=f"supplier-certificate-review:{certificate.id}",
        requested_outcome="Verify the evidence and record whether it is acceptable.",
    ))
    workflows.create_audit(db, user.tenant_id, user.plant_id, user.name, "supplier_certificate.submitted", "supplier_certificate", certificate.id, actor_user_id=user.id, meta={"supplier_id": supplier.id, "certificate_type": certificate_type})
    return certificate


def decide_supplier_certificate(
    db: Session, user: models.User, certificate_id: str, decision: str, notes: str,
) -> models.SupplierCertificate:
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_MANAGER, ADMIN)
    certificate = workflows.get_scoped_or_404(db, models.SupplierCertificate, user, certificate_id, "Supplier certificate")
    if certificate.status != "pending_review":
        raise HTTPException(status_code=409, detail="Only a pending supplier certificate can be reviewed")
    certificate.status = "verified" if decision == "verify" else "rejected"
    certificate.verified_by_user_id = user.id
    certificate.verified_at = utcnow()
    certificate.review_notes = notes
    supplier = workflows.get_scoped_or_404(db, models.Supplier, user, certificate.supplier_id, "Supplier")
    capability_items = {row.item_id for row in workflows.user_scope_query(db, models.SupplierItemCapability, user).filter_by(supplier_id=supplier.id, approved=True).all()}
    readiness = workflows.supplier_compliance_readiness(db, user, supplier, capability_items)
    if supplier.status != "blocked":
        supplier.status = "approved" if readiness["eligible"] else "conditional"
    for task in workflows.user_scope_query(db, models.Task, user).filter_by(
        entity_type="supplier_certificate", entity_id=certificate.id
    ).all():
        if task.status in {"open", "accepted", "in_progress", "review", "pending_approval"}:
            task.status = "completed"
            task.completed_at = utcnow()
            task.completion_summary = f"Evidence {certificate.status}: {notes or 'review completed'}"
    workflows.create_audit(db, user.tenant_id, user.plant_id, user.name, f"supplier_certificate.{certificate.status}", "supplier_certificate", certificate.id, actor_user_id=user.id, meta={"notes": notes, "supplier_status": supplier.status})
    return certificate


def _membership_for_role(
    db: Session, user: models.User, role: str
) -> tuple[models.WorkspaceMembership, models.User]:
    membership = db.query(models.WorkspaceMembership).filter(
        models.WorkspaceMembership.tenant_id == user.tenant_id,
        models.WorkspaceMembership.default_plant_id == user.plant_id,
        models.WorkspaceMembership.role == role,
        models.WorkspaceMembership.status == "active",
    ).order_by(models.WorkspaceMembership.created_at.asc()).first()
    employee = db.get(models.User, membership.user_id) if membership else None
    if membership is None or employee is None:
        raise HTTPException(status_code=409, detail=f"An active named {role.replace('_', ' ')} is required")
    return membership, employee


def _create_agent_handoff(
    db: Session, user: models.User, recipient: models.WorkspaceMembership,
    work_item: models.Task, requested_outcome: str,
) -> None:
    sender = agent_service.membership_for_user(db, user)
    sender_profile = db.query(models.AgentProfile).filter_by(
        tenant_id=user.tenant_id, membership_id=sender.id
    ).first()
    recipient_profile = db.query(models.AgentProfile).filter_by(
        tenant_id=user.tenant_id, membership_id=recipient.id
    ).first()
    if not sender_profile or not recipient_profile:
        return
    db.add(models.AgentDelegation(
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        sender_agent_profile_id=sender_profile.id, sender_membership_id=sender.id,
        recipient_agent_profile_id=recipient_profile.id, recipient_membership_id=recipient.id,
        work_item_id=work_item.id, requested_outcome=requested_outcome,
        context_packet={"entity_type": work_item.entity_type, "entity_id": work_item.entity_id},
        due_at=work_item.due_at, status="pending", response={}, depth=1,
    ))


def _approval_work(
    db: Session, user: models.User, comparison: models.BidComparison,
    artifact: models.GeneratedArtifact, role: str,
) -> models.ComparisonApprovalRequest:
    membership, employee = _membership_for_role(db, user, role)
    approval = models.ComparisonApprovalRequest(
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        comparison_id=comparison.id, comparison_version=comparison.comparison_version,
        required_role=role, assignee_membership_id=membership.id,
        status="pending", artifact_id=artifact.id,
    )
    db.add(approval)
    db.flush()
    task = models.Task(
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        title=f"Review supplier comparison v{comparison.comparison_version}",
        owner_role=role, owner_user_id=employee.id, owner_membership_id=membership.id,
        due_at=utcnow() + timedelta(hours=8), status="pending_approval",
        severity="critical", entity_type="bid_comparison", entity_id=comparison.id,
        assignment_source="workflow",
    )
    db.add(task)
    db.add(models.Notification(
        tenant_id=user.tenant_id, plant_id=user.plant_id, user_id=employee.id,
        title="Supplier comparison needs your approval",
        body=f"Comparison version {comparison.comparison_version} is ready. Review the PDF and recommendation before deciding.",
    ))
    db.add(models.OutboxMessage(
        tenant_id=user.tenant_id, plant_id=user.plant_id, channel="email",
        recipient=employee.email, subject=f"Comparison approval v{comparison.comparison_version}",
        body=f"Open the secure workspace to review comparison {comparison.id}.",
        status="approved_pending_send", payload_hash=workflows.payload_hash(f"{comparison.id}:{role}:{comparison.comparison_version}"),
        correlation_id=f"CMP-{comparison.id[:8]}-{role}", idempotency_key=f"comparison:{comparison.id}:v{comparison.comparison_version}:{role}",
        approved_by_user_id=user.id, approved_at=utcnow(), attachment_document_ids=[],
        meta={"comparison_id": comparison.id, "artifact_id": artifact.id, "secure_link": f"/documents/{artifact.document_id}/download-url"},
    ))
    db.flush()
    _create_agent_handoff(db, user, membership, task, "Review the comparison evidence and return a formal approval decision.")
    return approval


def submit_comparison(
    db: Session, user: models.User, comparison_id: str, rationale: str
) -> models.BidComparison:
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_MANAGER, ADMIN)
    comparison = workflows.get_scoped_or_404(db, models.BidComparison, user, comparison_id, "Comparison")
    if comparison.status not in {"draft", "ready_for_manager_review", "rejected"}:
        raise HTTPException(status_code=409, detail="Only a draft or rejected comparison can be submitted")
    if not comparison.recommended_supplier_id:
        raise HTTPException(status_code=409, detail="Select an eligible recommended supplier before submission")
    if comparison.status == "rejected":
        comparison.comparison_version += 1
    policy_result = procurement_policy.enforce_comparison(db, user, comparison, rationale)
    db.query(models.ComparisonApprovalRequest).filter_by(
        tenant_id=user.tenant_id, comparison_id=comparison.id, status="pending"
    ).update({models.ComparisonApprovalRequest.status: "invalidated"}, synchronize_session=False)
    comparison.recommendation_rationale = rationale
    comparison.status = "ready_for_approval"
    comparison.submitted_at = utcnow()
    comparison.submitted_by_user_id = user.id
    db.flush()
    artifact = generate_artifact(db, user, "comparison", comparison.id, final=True)
    for required_role in policy_result["required_approval_roles"]:
        if required_role not in {PLANT_MANAGER, PURCHASE_EXECUTIVE}:
            raise HTTPException(status_code=409, detail=f"Unsupported approval role in active procurement policy: {required_role}")
        _approval_work(db, user, comparison, artifact, required_role)
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name, "comparison.submitted",
        "bid_comparison", comparison.id, actor_user_id=user.id,
        meta={"version": comparison.comparison_version, "artifact_id": artifact.id, "policy_evaluation_id": policy_result.get("evaluation_id")},
    )
    return comparison


def decide_comparison(
    db: Session, user: models.User, comparison_id: str, decision: str, rationale: str
) -> models.BidComparison:
    require_procurement_v2(db, user)
    require_role(user, PLANT_MANAGER, PURCHASE_EXECUTIVE)
    comparison = workflows.get_scoped_or_404(db, models.BidComparison, user, comparison_id, "Comparison")
    membership = agent_service.membership_for_user(db, user)
    approval = db.query(models.ComparisonApprovalRequest).filter_by(
        tenant_id=user.tenant_id, comparison_id=comparison.id,
        comparison_version=comparison.comparison_version, required_role=user.role,
        assignee_membership_id=membership.id, status="pending",
    ).first()
    if approval is None:
        raise HTTPException(status_code=403, detail="No current named approval request is assigned to this membership")
    approval.status = "approved" if decision == "approve" else "rejected"
    approval.rationale = rationale
    approval.decided_by_user_id = user.id
    approval.decided_at = utcnow()
    tasks = db.query(models.Task).filter_by(
        tenant_id=user.tenant_id, entity_type="bid_comparison", entity_id=comparison.id,
        owner_membership_id=membership.id
    ).filter(models.Task.status.in_(["open", "pending_approval"])).all()
    for task in tasks:
        task.status = "completed"
        task.completed_at = utcnow()
    if decision == "reject":
        comparison.status = "rejected"
        db.query(models.ComparisonApprovalRequest).filter_by(
            tenant_id=user.tenant_id, comparison_id=comparison.id,
            comparison_version=comparison.comparison_version, status="pending",
        ).update({models.ComparisonApprovalRequest.status: "invalidated"}, synchronize_session=False)
        manager_membership, manager = _membership_for_role(db, user, PURCHASE_MANAGER)
        db.add(models.Task(
            tenant_id=user.tenant_id, plant_id=user.plant_id,
            title=f"Revise rejected comparison v{comparison.comparison_version}",
            owner_role=PURCHASE_MANAGER, owner_user_id=manager.id,
            owner_membership_id=manager_membership.id, status="open", severity="critical",
            due_at=utcnow() + timedelta(hours=4), entity_type="bid_comparison", entity_id=comparison.id,
        ))
    else:
        db.flush()
        pending = db.query(models.ComparisonApprovalRequest).filter_by(
            tenant_id=user.tenant_id, comparison_id=comparison.id,
            comparison_version=comparison.comparison_version, status="pending",
        ).count()
        comparison.status = "approved" if pending == 0 else "partially_approved"
        if comparison.status == "approved":
            manager_membership, manager = _membership_for_role(db, user, PURCHASE_MANAGER)
            db.add(models.Task(
                tenant_id=user.tenant_id, plant_id=user.plant_id,
                title=f"Confirm purchase order from comparison v{comparison.comparison_version}",
                owner_role=PURCHASE_MANAGER, owner_user_id=manager.id,
                owner_membership_id=manager_membership.id, status="pending_approval",
                severity="critical", due_at=utcnow() + timedelta(hours=4),
                entity_type="bid_comparison", entity_id=comparison.id,
            ))
    workflows.record_approval(
        db, user, f"bid_comparison_v{comparison.comparison_version}_{user.role}",
        comparison.id, approval.status, rationale,
    )
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name, f"comparison.{approval.status}",
        "bid_comparison", comparison.id, actor_user_id=user.id,
        meta={"version": comparison.comparison_version, "role": user.role, "rationale": rationale},
    )
    return comparison


def confirm_purchase_order(
    db: Session, user: models.User, comparison_id: str
) -> tuple[models.PODraft, models.GeneratedArtifact]:
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_MANAGER, ADMIN)
    comparison = workflows.get_scoped_or_404(db, models.BidComparison, user, comparison_id, "Comparison")
    if comparison.status != "approved":
        raise HTTPException(status_code=409, detail="Both named comparison approvals are required before PO creation")
    row = next((item for item in comparison.rows if item.get("supplier_id") == comparison.recommended_supplier_id), None)
    if not row:
        raise HTTPException(status_code=409, detail="The approved supplier quote is unavailable")
    award = workflows.user_scope_query(db, models.AwardDecision, user).filter_by(
        rfq_id=comparison.rfq_id, supplier_id=comparison.recommended_supplier_id
    ).first()
    if award is None:
        award = models.AwardDecision(
            tenant_id=user.tenant_id, plant_id=user.plant_id,
            business_number=workflows.next_business_number(db, "AWARD", user),
            rfq_id=comparison.rfq_id, quote_id=row["quote_id"],
            supplier_id=comparison.recommended_supplier_id, status="approved",
            approved_by_user_id=user.id, approved_at=utcnow(),
            rationale=comparison.recommendation_rationale,
        )
        db.add(award)
        db.flush()
    po = workflows.create_po_draft_for_award(db, user, award)
    if po.status == "pending_approval":
        po.status = "approved_pending_outbox"
        po.approved_by_user_id = user.id
        po.approved_at = utcnow()
    artifact = generate_artifact(db, user, "po", po.id, final=True)
    existing_event = workflows.user_scope_query(db, models.IntegrationOutboxEvent, user).filter_by(
        entity_type="po_draft", entity_id=po.id, action="push_purchase_order"
    ).first()
    if existing_event is None:
        workflows.create_integration_outbox_event(
            db, user, get_settings().erp_provider or "local",
            "push_purchase_order", "po_draft", po.id, po.oracle_mapping,
            approved=False,
        )
    workflows.complete_tasks_for_entity(db, user, "bid_comparison", comparison.id)
    workflows.complete_tasks_for_entity(db, user, "po_drafts", po.id)
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name, "po.final_created",
        "po_draft", po.id, actor_user_id=user.id,
        meta={"comparison_id": comparison.id, "comparison_version": comparison.comparison_version,
              "artifact_id": artifact.id, "erp_posted": False, "supplier_sent": False},
    )
    return po, artifact


def confirm_split_purchase_orders(
    db: Session,
    user: models.User,
    comparison_id: str,
    allocations: list[dict[str, Any]],
) -> tuple[models.AwardBatch, list[models.PODraft]]:
    """Confirm one immutable allocation set and create one PO per supplier quote."""
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_MANAGER, ADMIN)
    comparison = workflows.get_scoped_or_404(db, models.BidComparison, user, comparison_id, "Comparison")
    if comparison.status != "approved":
        raise HTTPException(status_code=409, detail="Both named comparison approvals are required before confirming an award")
    if not allocations:
        raise HTTPException(status_code=422, detail="At least one supplier allocation is required")

    normalized = sorted(
        ({
            "rfq_line_id": str(row.get("rfq_line_id", "")),
            "quote_line_id": str(row.get("quote_line_id", "")),
            "awarded_quantity": float(row.get("awarded_quantity", 0)),
            "rationale": str(row.get("rationale", "")),
        } for row in allocations),
        key=lambda row: (row["rfq_line_id"], row["quote_line_id"]),
    )
    allocation_hash = hashlib.sha256(json.dumps(normalized, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
    existing = workflows.user_scope_query(db, models.AwardBatch, user).filter_by(
        comparison_id=comparison.id, comparison_version=comparison.comparison_version,
    ).first()
    if existing:
        if existing.allocation_hash != allocation_hash:
            raise HTTPException(status_code=409, detail="This approved comparison version already has a confirmed supplier allocation")
        awards = workflows.user_scope_query(db, models.AwardDecision, user).filter_by(award_batch_id=existing.id).all()
        purchase_orders = [
            workflows.user_scope_query(db, models.PODraft, user).filter_by(award_id=award.id).one()
            for award in awards
        ]
        return existing, purchase_orders

    rfq = workflows.get_scoped_or_404(db, models.RFQ, user, comparison.rfq_id, "Supplier request")
    rfq_lines = {line.id: line for line in workflows.user_scope_query(db, models.RFQLine, user).filter_by(rfq_id=rfq.id).all()}
    rfq_totals: dict[str, float] = {}
    quote_totals: dict[str, float] = {}
    resolved: list[tuple[dict[str, Any], models.RFQLine, models.QuoteLine, models.SupplierQuote]] = []
    for row in normalized:
        if row["awarded_quantity"] <= 0:
            raise HTTPException(status_code=422, detail="Award quantities must be positive")
        rfq_line = rfq_lines.get(row["rfq_line_id"])
        if rfq_line is None:
            raise HTTPException(status_code=422, detail="An allocated line does not belong to this supplier request")
        quote_line = workflows.get_scoped_or_404(db, models.QuoteLine, user, row["quote_line_id"], "Quotation line")
        quote = workflows.get_scoped_or_404(db, models.SupplierQuote, user, quote_line.quote_id, "Quotation")
        if quote.rfq_id != rfq.id or quote.verification_status != "verified" or quote_line.rfq_line_id != rfq_line.id:
            raise HTTPException(status_code=409, detail="Every allocation must use a current verified quotation line for the selected supplier request")
        rfq_totals[rfq_line.id] = rfq_totals.get(rfq_line.id, 0) + row["awarded_quantity"]
        quote_totals[quote_line.id] = quote_totals.get(quote_line.id, 0) + row["awarded_quantity"]
        if rfq_totals[rfq_line.id] > rfq_line.quantity:
            raise HTTPException(status_code=422, detail="Allocated quantity exceeds the requested line quantity")
        if quote_totals[quote_line.id] > quote_line.quantity:
            raise HTTPException(status_code=422, detail="Allocated quantity exceeds the supplier's offered quantity")
        resolved.append((row, rfq_line, quote_line, quote))

    batch = models.AwardBatch(
        business_number=workflows.next_business_number(db, "AWARD-BATCH", user),
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        comparison_id=comparison.id, comparison_version=comparison.comparison_version,
        allocation_hash=allocation_hash, status="confirmed", created_by_user_id=user.id,
        total_awarded_quantity=sum(row["awarded_quantity"] for row in normalized),
    )
    db.add(batch)
    db.flush()
    grouped: dict[tuple[str, str], list[tuple[dict[str, Any], models.RFQLine, models.QuoteLine]]] = {}
    for row, rfq_line, quote_line, quote in resolved:
        grouped.setdefault((quote.supplier_id, quote.id), []).append((row, rfq_line, quote_line))
    policy = procurement_policy.active_policy(db, user)
    if len(grouped) > 1 and not procurement_policy.policy_rules(policy).get("allow_split_awards", True):
        raise HTTPException(status_code=409, detail="The active procurement policy does not permit split supplier awards")

    purchase_orders: list[models.PODraft] = []
    for (supplier_id, quote_id), rows in grouped.items():
        award = models.AwardDecision(
            business_number=workflows.next_business_number(db, "AWARD", user),
            tenant_id=user.tenant_id, plant_id=user.plant_id, award_batch_id=batch.id,
            rfq_id=rfq.id, quote_id=quote_id, supplier_id=supplier_id, status="approved",
            approved_by_user_id=user.id, approved_at=utcnow(),
            rationale="; ".join(filter(None, (row[0]["rationale"] for row in rows))) or comparison.recommendation_rationale,
        )
        db.add(award)
        db.flush()
        for row, rfq_line, quote_line in rows:
            db.add(models.AwardLine(
                tenant_id=user.tenant_id, plant_id=user.plant_id, award_id=award.id,
                rfq_line_id=rfq_line.id, quote_line_id=quote_line.id,
                supplier_id=supplier_id, awarded_quantity=row["awarded_quantity"],
                rationale=row["rationale"],
            ))
        db.flush()
        po = workflows.create_po_draft_for_award(db, user, award)
        po.status = "approved_pending_outbox"
        po.approved_by_user_id = user.id
        po.approved_at = utcnow()
        generate_artifact(db, user, "po", po.id, final=True)
        existing_event = workflows.user_scope_query(db, models.IntegrationOutboxEvent, user).filter_by(
            entity_type="po_draft", entity_id=po.id, action="push_purchase_order",
        ).first()
        if existing_event is None:
            workflows.create_integration_outbox_event(
                db, user, get_settings().erp_provider or "local", "push_purchase_order",
                "po_draft", po.id, po.oracle_mapping, approved=False,
            )
        purchase_orders.append(po)

    workflows.complete_tasks_for_entity(db, user, "bid_comparison", comparison.id)
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name, "split_award.confirmed",
        "award_batch", batch.id, actor_user_id=user.id,
        meta={"comparison_id": comparison.id, "comparison_version": comparison.comparison_version,
              "po_ids": [po.id for po in purchase_orders], "allocation_hash": allocation_hash},
    )
    return batch, purchase_orders


def recommended_award_allocations(
    db: Session, user: models.User, comparison: models.BidComparison,
) -> list[dict[str, Any]]:
    """Resolve approved per-line recommendations into an explicit preview."""
    allocations: list[dict[str, Any]] = []
    rows = [row for row in (comparison.rows or []) if row.get("recommendation") == "Recommended" and not row.get("disqualified")]
    for row in rows:
        quote_line = workflows.get_scoped_or_404(db, models.QuoteLine, user, str(row.get("quote_line_id") or ""), "Quotation line")
        rfq_line = workflows.get_scoped_or_404(db, models.RFQLine, user, str(row.get("rfq_line_id") or quote_line.rfq_line_id or ""), "Supplier-request line")
        allocations.append({
            "rfq_line_id": rfq_line.id, "quote_line_id": quote_line.id,
            "awarded_quantity": min(float(rfq_line.quantity), float(quote_line.quantity)),
            "rationale": "Approved comparison recommendation",
            "supplier_id": str(row.get("supplier_id") or ""),
            "supplier_name": str(row.get("supplier_name") or ""),
        })
    if not allocations:
        raise HTTPException(status_code=409, detail="The approved comparison has no eligible line recommendation")
    return allocations


def prepare_po_supplier_email(
    db: Session, user: models.User, po_draft_id: str
) -> models.OutboxMessage:
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_MANAGER, ADMIN)
    po = workflows.get_scoped_or_404(db, models.PODraft, user, po_draft_id, "PO")
    if po.status not in {"approved_pending_outbox", "simulated_posted", "posted"}:
        raise HTTPException(status_code=409, detail="Only a final purchase order can be sent")
    existing = workflows.user_scope_query(db, models.OutboxMessage, user).filter_by(
        idempotency_key=f"po:{po.id}:supplier-copy"
    ).first()
    if existing:
        return existing
    contact = workflows.user_scope_query(db, models.SupplierContact, user).filter_by(
        supplier_id=po.supplier_id
    ).first()
    if contact is None:
        raise HTTPException(status_code=409, detail="Supplier contact is required")
    # Re-evaluate the immutable snapshot before delivery. This idempotently
    # creates a corrected version for older POs whose first PDF was rendered
    # before pending lines were flushed.
    artifact = generate_artifact(db, user, "po", po.id, final=True)
    message = models.OutboxMessage(
        tenant_id=user.tenant_id, plant_id=user.plant_id, channel="email",
        recipient=contact.email, subject=f"Purchase order {po.business_number or po.id}",
        body="Please find the approved purchase order attached. Acknowledgement instructions will follow the controlled supplier workflow.",
        status="approved_pending_send", payload_hash=workflows.payload_hash(po.oracle_mapping),
        correlation_id=f"PO-MAIL-{po.id[:12]}",
        idempotency_key=f"po:{po.id}:supplier-copy",
        approved_by_user_id=user.id, approved_at=utcnow(),
        attachment_document_ids=[artifact.document_id],
        meta={"po_draft_id": po.id, "artifact_id": artifact.id},
    )
    db.add(message)
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name,
        "po.supplier_email_prepared", "po_draft", po.id,
        actor_user_id=user.id, meta={"outbox_id": message.id, "artifact_id": artifact.id},
    )
    return message


def prepare_po_change(
    db: Session, user: models.User, po_draft_id: str, change_type: str,
    reason: str, line_changes: list[dict[str, Any]], acknowledgement_id: str | None = None,
) -> models.PODraft:
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_MANAGER, ADMIN)
    current = workflows.get_scoped_or_404(db, models.PODraft, user, po_draft_id, "Purchase order")
    if current.status not in {"posted", "simulated_posted"}:
        raise HTTPException(status_code=409, detail="Only an issued purchase order can be amended or cancelled")
    if change_type not in {"amendment", "cancellation"}:
        raise HTTPException(status_code=422, detail="Change type must be amendment or cancellation")
    root_id = current.root_po_id or current.id
    pending = workflows.user_scope_query(db, models.PODraft, user).filter(
        models.PODraft.root_po_id == root_id,
        models.PODraft.status.in_(["pending_approval", "approved_pending_outbox", "posting"]),
    ).first()
    if pending:
        raise HTTPException(status_code=409, detail="A purchase-order change is already awaiting approval or dispatch")
    receipts = workflows.user_scope_query(db, models.StoreReceipt, user).filter_by(po_draft_id=current.id).all()
    asns = workflows.user_scope_query(db, models.ASN, user).filter_by(po_draft_id=current.id).all()
    if change_type == "cancellation" and (receipts or asns):
        raise HTTPException(status_code=409, detail="An order with delivery or receipt activity cannot be cancelled; use a quantity amendment or return workflow")
    source_lines = workflows.user_scope_query(db, models.PODraftLine, user).filter_by(po_draft_id=current.id).all()
    if not source_lines:
        raise HTTPException(status_code=409, detail="Purchase order has no lines")
    changes = {str(row.get("line_id") or ""): row for row in line_changes}
    if change_type == "amendment" and not changes:
        raise HTTPException(status_code=422, detail="At least one line change is required for an amendment")
    unknown = set(changes) - {line.id for line in source_lines}
    if unknown:
        raise HTTPException(status_code=422, detail="A changed line does not belong to this purchase-order version")
    latest_version = workflows.user_scope_query(db, models.PODraft, user).filter(
        (models.PODraft.id == root_id) | (models.PODraft.root_po_id == root_id),
    ).order_by(models.PODraft.revision_number.desc()).first()
    revision_number = (latest_version.revision_number if latest_version else current.revision_number) + 1
    revision = models.PODraft(
        business_number=f"{(current.business_number or current.id).split('/V')[0]}/V{revision_number}",
        tenant_id=user.tenant_id, plant_id=user.plant_id, award_id=current.award_id,
        supplier_id=current.supplier_id, supplier_site_id=current.supplier_site_id,
        status="pending_approval", oracle_mapping=json.loads(json.dumps(current.oracle_mapping or {})),
        currency=current.currency, payment_terms=current.payment_terms,
        commercial_terms=json.loads(json.dumps(current.commercial_terms or {})),
        root_po_id=root_id, previous_version_id=current.id, revision_number=revision_number,
        revision_kind=change_type, change_reason=reason, change_summary={},
    )
    db.add(revision)
    db.flush()
    summary_lines: list[dict[str, Any]] = []
    mapped_lines: list[dict[str, Any]] = []
    for index, source in enumerate(source_lines):
        change = changes.get(source.id, {})
        quantity = float(change.get("quantity") if change.get("quantity") is not None else source.quantity)
        unit_price = float(change.get("unit_price") if change.get("unit_price") is not None else source.unit_price)
        need_by = str(change.get("need_by_date") or source.need_by_date)
        new_line = models.PODraftLine(
            tenant_id=user.tenant_id, plant_id=user.plant_id, po_draft_id=revision.id,
            award_line_id=source.award_line_id, item_id=source.item_id, quantity=quantity,
            uom=source.uom, unit_price=unit_price, gst_rate=source.gst_rate,
            need_by_date=need_by, inspection_required=source.inspection_required,
        )
        db.add(new_line)
        prior_mapping = (current.oracle_mapping.get("lines") or [{}])[index] if index < len(current.oracle_mapping.get("lines") or []) else {}
        mapped_lines.append({**prior_mapping, "quantity": quantity, "unit_price": unit_price, "need_by_date": need_by})
        if change:
            summary_lines.append({
                "source_line_id": source.id,
                "quantity": {"from": source.quantity, "to": quantity},
                "unit_price": {"from": source.unit_price, "to": unit_price},
                "need_by_date": {"from": source.need_by_date, "to": need_by},
            })
    total_received = sum(receipt.received_quantity for receipt in receipts)
    if change_type == "amendment" and sum(line["quantity"] for line in mapped_lines) < total_received:
        raise HTTPException(status_code=409, detail="Amended quantity cannot be lower than quantity already received")
    revision.oracle_mapping["lines"] = mapped_lines
    revision.oracle_mapping.update({"operation": change_type, "original_po_id": root_id, "previous_version_id": current.id, "revision_number": revision_number})
    if len(mapped_lines) == 1:
        revision.oracle_mapping.update(mapped_lines[0])
    revision.change_summary = {"type": change_type, "lines": summary_lines, "reason": reason}
    if acknowledgement_id:
        acknowledgement = workflows.get_scoped_or_404(db, models.SupplierAcknowledgement, user, acknowledgement_id, "Supplier acknowledgement")
        if acknowledgement.po_draft_id != current.id or acknowledgement.status != "change_requested":
            raise HTTPException(status_code=409, detail="Only an open supplier change request for this purchase order can be linked")
        acknowledgement.status = "change_prepared"
        acknowledgement.reviewed_by_user_id = user.id
        acknowledgement.reviewed_at = utcnow()
        acknowledgement.linked_po_revision_id = revision.id
        revision.change_summary["supplier_acknowledgement"] = acknowledgement.business_number or acknowledgement.id
        for task in workflows.user_scope_query(db, models.Task, user).filter_by(
            entity_type="supplier_acknowledgements", entity_id=acknowledgement.id
        ).filter(models.Task.status.in_(["open", "accepted", "in_progress", "review"])).all():
            task.status = "completed"
            task.completed_at = utcnow()
            task.completion_summary = f"Supplier request linked to {revision.business_number}."
    membership, manager = _membership_for_role(db, user, PURCHASE_MANAGER)
    db.add(models.Task(
        tenant_id=user.tenant_id, plant_id=user.plant_id,
        title=f"Approve PO {change_type} {(current.business_number or current.id)} v{revision_number}",
        owner_role=PURCHASE_MANAGER, owner_user_id=manager.id, owner_membership_id=membership.id,
        status="pending_approval", severity="critical", due_at=utcnow() + timedelta(hours=4),
        entity_type="po_drafts", entity_id=revision.id,
    ))
    workflows.create_audit(db, user.tenant_id, user.plant_id, user.name, f"po.{change_type}.prepared", "po_draft", revision.id, actor_user_id=user.id, meta=revision.change_summary)
    return revision


def approve_po_change(db: Session, user: models.User, revision_id: str) -> models.PODraft:
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_MANAGER, ADMIN)
    revision = workflows.get_scoped_or_404(db, models.PODraft, user, revision_id, "Purchase-order change")
    if revision.revision_kind not in {"amendment", "cancellation"} or revision.status != "pending_approval":
        raise HTTPException(status_code=409, detail="Only a pending amendment or cancellation can be approved")
    previous = workflows.get_scoped_or_404(db, models.PODraft, user, str(revision.previous_version_id or ""), "Previous purchase-order version")
    if previous.status not in {"posted", "simulated_posted"}:
        raise HTTPException(status_code=409, detail="The previous issued version is no longer current")
    revision.status = "approved_pending_outbox"
    revision.approved_by_user_id = user.id
    revision.approved_at = utcnow()
    artifact = generate_artifact(db, user, "po", revision.id, final=True)
    action = "amend_purchase_order" if revision.revision_kind == "amendment" else "cancel_purchase_order"
    workflows.create_integration_outbox_event(
        db, user, get_settings().erp_provider or "local", action, "po_draft", revision.id,
        revision.oracle_mapping, approved=False,
    )
    workflows.record_approval(db, user, "po_change", revision.id, "approved", revision.change_reason)
    workflows.complete_tasks_for_entity(db, user, "po_drafts", revision.id)
    workflows.create_audit(db, user.tenant_id, user.plant_id, user.name, f"po.{revision.revision_kind}.approved", "po_draft", revision.id, actor_user_id=user.id, meta={"previous_version_id": previous.id, "artifact_id": artifact.id, "external_dispatched": False})
    date_changes = [
        row for row in (revision.change_summary or {}).get("lines", [])
        if (row.get("need_by_date") or {}).get("from") != (row.get("need_by_date") or {}).get("to")
    ]
    if date_changes:
        from app.platform.events import DomainEvent, publish
        membership = db.query(models.WorkspaceMembership).filter_by(
            tenant_id=user.tenant_id, user_id=user.id, status="active",
        ).first()
        publish(db, DomainEvent(
            event_type="procurement.po.delivery_rescheduled", tenant_id=user.tenant_id,
            plant_id=user.plant_id, subject_type="purchase_order", subject_id=revision.id,
            actor_membership_id=membership.id if membership else None,
            payload={
                "po_revision_id": revision.id, "previous_version_id": previous.id,
                "root_po_id": revision.root_po_id or previous.id,
                "supplier_id": revision.supplier_id, "date_changes": date_changes,
                "item_ids": [line.item_id for line in db.query(models.PODraftLine).filter_by(po_draft_id=revision.id).all()],
            }, source_system="procurement",
        ))
    return revision


def prepare_supplier_followup(
    db: Session, user: models.User, rfq_id: str, supplier_id: str, body: str,
) -> models.OutboxMessage:
    """Create an idempotent, approved delivery-queue record after human confirmation."""
    require_procurement_v2(db, user)
    require_role(user, PURCHASE_EXECUTIVE, PURCHASE_MANAGER, ADMIN)
    rfq = workflows.get_scoped_or_404(db, models.RFQ, user, rfq_id, "Supplier request")
    supplier = workflows.get_scoped_or_404(db, models.Supplier, user, supplier_id, "Supplier")
    if supplier.id not in (rfq.supplier_ids or []):
        raise HTTPException(status_code=409, detail="Supplier is not included in this supplier request")
    message_body = body.strip()
    if not message_body:
        raise HTTPException(status_code=422, detail="A supplier follow-up message is required")
    contact = workflows.user_scope_query(db, models.SupplierContact, user).filter_by(
        supplier_id=supplier.id,
    ).first()
    if contact is None or not contact.email:
        raise HTTPException(status_code=409, detail="Supplier contact email is required")
    message_hash = hashlib.sha256(message_body.encode()).hexdigest()
    idempotency_key = f"rfq:{rfq.id}:supplier:{supplier.id}:followup:{message_hash[:20]}"
    existing = workflows.user_scope_query(db, models.OutboxMessage, user).filter_by(
        idempotency_key=idempotency_key,
    ).first()
    if existing:
        return existing
    message = models.OutboxMessage(
        tenant_id=user.tenant_id, plant_id=user.plant_id, channel="email",
        recipient=contact.email,
        subject=f"Follow-up on supplier request {rfq.business_number or rfq.id}",
        body=message_body, status="approved_pending_send", payload_hash=message_hash,
        correlation_id=f"RFQ-FOLLOWUP-{rfq.id[:10]}-{supplier.id[:8]}",
        idempotency_key=idempotency_key, approved_by_user_id=user.id,
        approved_at=utcnow(), attachment_document_ids=[],
        meta={"rfq_id": rfq.id, "supplier_id": supplier.id, "message_type": "supplier_followup"},
    )
    db.add(message)
    workflows.create_audit(
        db, user.tenant_id, user.plant_id, user.name,
        "rfq.supplier_followup_prepared", "rfq", rfq.id,
        actor_user_id=user.id, meta={"supplier_id": supplier.id, "outbox_id": message.id},
    )
    return message
