"use client";

import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowUpRight, GitCompare, Play, Plus, RefreshCw, Truck } from "lucide-react";
import { useState } from "react";
import { addSCMScenarioOverride, compareSCMScenario, createSCMScenario, getSCMActions, getSCMHorizon,
  getSCMReadiness, getSCMScenarios, getSCMSuppliers, runSCMScenario, type SCMScenario } from "@/lib/scm-api";
import { SCMFrame } from "./SCMShell";

function State({text}:{text:string}){return <div className="scm-state"><RefreshCw className="spin"/><h2>{text}</h2></div>}
function ErrorState(){return <div className="scm-state error"><AlertTriangle/><h2>This planning view is unavailable</h2><p>The request could not be completed. Run planning, then retry this view.</p></div>}

function Horizon(){const[days,setDays]=useState(210);const[risk,setRisk]=useState("");const query=useQuery({queryKey:["scm-horizon",days,risk],queryFn:()=>getSCMHorizon(days,risk)});if(query.isLoading)return <State text="Preparing the supply horizon"/>;if(query.error)return <ErrorState/>;const data=query.data!;return <><PageHead eyebrow="SUPPLY HORIZON" title="See the next problem before it reaches production." text="A dense, scrollable material timeline with shortage bands and confirmed receipt markers."/><div className="scm-filters"><label>Window<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[30,90,210,365].map(v=><option key={v} value={v}>{v} days</option>)}</select></label><label>Risk<select value={risk} onChange={e=>setRisk(e.target.value)}><option value="">All states</option><option>CRITICAL</option><option>AT_RISK</option><option>EXCESS</option></select></label></div><section className="scm-panel horizon"><header><div><span>VIRTUALIZED MATERIAL ROWS</span><h2>{data.rows.length} material timelines</h2></div></header><div className="horizon-axis"><b>Material</b><span>Now</span><span>{Math.round(days/3)}d</span><span>{Math.round(days*2/3)}d</span><span>{days}d</span></div><div className="horizon-scroll">{data.rows.map(row=><Link href={`/scm/materials/${row.material.id}`} className="horizon-row" key={row.material.id}><div><strong>{row.material.code}</strong><small>{row.material.description}</small></div><div className="horizon-track">{row.points.filter((_,i)=>i%Math.max(1,Math.floor(days/70))===0).map(point=><i key={point.date} className={point.status.toLowerCase()} title={`${point.date}: ${point.closing}`}/>) }{row.receipts.map(receipt=><em key={`${receipt.date}-${receipt.source_id}`} style={{left:`${Math.max(0,Math.min(100,(new Date(receipt.date).getTime()-new Date(data.run!.horizon_start).getTime())/86400000/days*100))}%`}} title={`${receipt.source_id}: +${receipt.quantity}`}>▲</em>)}</div></Link>)}</div></section></>}

function Readiness(){const query=useQuery({queryKey:["scm-readiness"],queryFn:getSCMReadiness});if(query.isLoading)return <State text="Calculating product readiness"/>;if(query.error)return <ErrorState/>;const data=query.data!;return <><PageHead eyebrow="PRODUCT / OEM READINESS" title="Which production commitments are material-ready?" text="One missing component blocks the product; percentages support, but never replace, the operational status."/><section className="scm-kpis three">{["READY","AT_RISK","BLOCKED"].map(status=><article key={status} className={status==="BLOCKED"?"danger":""}><span>{status.replace("_"," ")}</span><strong>{data.summary[status]??0}</strong><small>product requirements</small></article>)}</section><section className="scm-table"><div className="scm-table-head readiness"><span>Product</span><span>Required</span><span>Coverage</span><span>Blocking</span><span>Status</span></div>{data.products.map(row=><div className="scm-table-row readiness" key={row.id}><div><strong>{row.product.code}</strong><small>{row.product.name}{row.work_order_id&&` · ${row.work_order_id}`}</small></div><span>{row.required_date}</span><span>{row.covered_components}/{row.total_components}</span><span>{row.blocking_components}</span><span className={`scm-badge ${row.status.toLowerCase()}`}>{row.status}</span></div>)}</section></>}

function Actions(){const query=useQuery({queryKey:["scm-actions"],queryFn:getSCMActions});if(query.isLoading)return <State text="Loading governed actions"/>;if(query.error)return <ErrorState/>;return <><PageHead eyebrow="ACTION CENTER" title="Decisions, approvals, execution and recovery." text="Execution success and operational recovery are shown separately."/><section className="scm-table"><div className="scm-table-head actions"><span>Action</span><span>Target</span><span>Policy / approval</span><span>Execution</span><span>Verification</span></div>{query.data?.map(row=><div className="scm-table-row actions" key={row.id}><div><strong>{row.action_type.replaceAll("_"," ")}</strong><small>{row.reason}</small></div><span>{row.target_type} · {row.target_id}</span><span>{row.approval?.decision??row.status}</span><span>{row.execution?.status??"Not started"}</span><span className={`scm-badge ${(row.outcome?.verification_status??"pending").toLowerCase()}`}>{row.outcome?.verification_status??"Pending"}</span></div>)}</section></>}

function Scenarios(){const client=useQueryClient();const[name,setName]=useState("");const[selected,setSelected]=useState<SCMScenario|null>(null);const[comparison,setComparison]=useState<Record<string,Record<string,number>>|null>(null);const query=useQuery({queryKey:["scm-scenarios"],queryFn:getSCMScenarios});const create=useMutation({mutationFn:()=>createSCMScenario(name,"Planner what-if"),onSuccess:()=>{setName("");client.invalidateQueries({queryKey:["scm-scenarios"]})}});const run=useMutation({mutationFn:(id:string)=>runSCMScenario(id),onSuccess:()=>client.invalidateQueries({queryKey:["scm-scenarios"]})});async function compare(id:string){setComparison(await compareSCMScenario(id))}return <><PageHead eyebrow="SCENARIO LAB" title="Change assumptions without changing reality." text="Every scenario runs from an immutable baseline snapshot and remains isolated from operational planning."/><div className="scenario-create"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Scenario name"/><button disabled={name.length<3} onClick={()=>create.mutate()}><Plus/>Save scenario</button></div><div className="scenario-layout"><section className="scm-panel"><header><div><span>SAVED SCENARIOS</span><h2>What-if workspace</h2></div></header>{query.data?.map(row=><button className="scenario-row" key={row.id} onClick={()=>setSelected(row)}><GitCompare/><div><strong>{row.name}</strong><small>{row.overrides.length} overrides · {row.result_run_id?"simulated":"not run"}</small></div></button>)}</section><section className="scm-panel scenario-detail"><header><div><span>INPUTS / RESULT</span><h2>{selected?.name??"Select a scenario"}</h2></div></header>{selected&&<><button onClick={()=>run.mutate(selected.id)}><Play/>Run isolated simulation</button>{selected.result_run_id&&<button className="secondary" onClick={()=>compare(selected.id)}>Compare baseline</button>}<button className="ghost" onClick={()=>addSCMScenarioOverride(selected.id,{material_id:"",override_type:"DEMAND",values:{factor:1.15},reason:"Demand sensitivity"})}>+15% demand template</button>{comparison&&<div className="scenario-metrics">{Object.entries(comparison.delta??{}).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><strong>{value>0?"+":""}{value}</strong></div>)}</div>}</>}</section></div></>}

function Suppliers(){const query=useQuery({queryKey:["scm-suppliers"],queryFn:getSCMSuppliers});if(query.isLoading)return <State text="Building supplier exposure"/>;if(query.error)return <ErrorState/>;return <><PageHead eyebrow="SUPPLIER CONTROL CENTER / V1.5" title="Commitment reliability meets material exposure." text="Open supply, confirmation gaps and delays are calculated from existing canonical supplier and PO data."/><section className="scm-table"><div className="scm-table-head supplier"><span>Supplier</span><span>Materials</span><span>Open POs</span><span>Confirmed</span><span>Unconfirmed</span><span>Delayed</span></div>{query.data?.map(row=><div className="scm-table-row supplier" key={row.id}><div><strong>{row.name}</strong><small>{row.code}</small></div><span>{row.materials_supplied}</span><span>{row.open_pos}</span><span>{row.confirmed}</span><span>{row.unconfirmed}</span><span className={row.delayed?"danger-text":""}>{row.delayed}</span></div>)}</section></>}

function PageHead({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <header className="scm-page-head"><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></header>}
export function SCMRemainingWorkspace({view}:{view:"horizon"|"readiness"|"actions"|"scenarios"|"suppliers"}){return <SCMFrame>{{horizon:<Horizon/>,readiness:<Readiness/>,actions:<Actions/>,scenarios:<Scenarios/>,suppliers:<Suppliers/>}[view]}</SCMFrame>}
